#' Google Spectrum Database API
#' API for spectrum-management functions.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 20:15:32
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlespectrumv1explorer.auto/R/spectrum_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item 
#' }
#' 
#' @docType package 
#' @name spectrum_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Requests information about the available spectrum for a device at a location. Requests from a fixed-mode device must include owner information so the device can be registered with the database.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsGetSpectrumRequest The \link{PawsGetSpectrumRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsGetSpectrumRequest functions
#' @export
paws.getSpectrum <- function(PawsGetSpectrumRequest) {
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/getSpectrum"
    # spectrum.paws.getSpectrum
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PawsGetSpectrumRequest, "gar_PawsGetSpectrumRequest"))
    
    f(the_body = PawsGetSpectrumRequest)
    
}

#' The Google Spectrum Database does not support batch requests, so this method always yields an UNIMPLEMENTED error.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsGetSpectrumBatchRequest The \link{PawsGetSpectrumBatchRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsGetSpectrumBatchRequest functions
#' @export
paws.getSpectrumBatch <- function(PawsGetSpectrumBatchRequest) {
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/getSpectrumBatch"
    # spectrum.paws.getSpectrumBatch
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PawsGetSpectrumBatchRequest, "gar_PawsGetSpectrumBatchRequest"))
    
    f(the_body = PawsGetSpectrumBatchRequest)
    
}

#' Initializes the connection between a white space device and the database.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsInitRequest The \link{PawsInitRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsInitRequest functions
#' @export
paws.init <- function(PawsInitRequest) {
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/init"
    # spectrum.paws.init
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PawsInitRequest, "gar_PawsInitRequest"))
    
    f(the_body = PawsInitRequest)
    
}

#' Notifies the database that the device has selected certain frequency ranges for transmission. Only to be invoked when required by the regulator. The Google Spectrum Database does not operate in domains that require notification, so this always yields an UNIMPLEMENTED error.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsNotifySpectrumUseRequest The \link{PawsNotifySpectrumUseRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsNotifySpectrumUseRequest functions
#' @export
paws.notifySpectrumUse <- function(PawsNotifySpectrumUseRequest) {
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/notifySpectrumUse"
    # spectrum.paws.notifySpectrumUse
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PawsNotifySpectrumUseRequest, "gar_PawsNotifySpectrumUseRequest"))
    
    f(the_body = PawsNotifySpectrumUseRequest)
    
}

#' The Google Spectrum Database implements registration in the getSpectrum method. As such this always returns an UNIMPLEMENTED error.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsRegisterRequest The \link{PawsRegisterRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsRegisterRequest functions
#' @export
paws.register <- function(PawsRegisterRequest) {
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/register"
    # spectrum.paws.register
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PawsRegisterRequest, "gar_PawsRegisterRequest"))
    
    f(the_body = PawsRegisterRequest)
    
}


#' Validates a device for white space use in accordance with regulatory rules. The Google Spectrum Database does not support master/slave configurations, so this always yields an UNIMPLEMENTED error.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{http://developers.google.com/spectrum}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PawsVerifyDeviceRequest The \link{PawsVerifyDeviceRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family PawsVerifyDeviceRequest functions
#' @export


paws.verifyDevice <- function(PawsVerifyDeviceRequest) {
    
    
    url <- "https://www.googleapis.com/spectrum/v1explorer/paws/verifyDevice"
    # spectrum.paws.verifyDevice
    
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    
    stopifnot(inherits(PawsVerifyDeviceRequest, "gar_PawsVerifyDeviceRequest"))
    
    f(the_body = PawsVerifyDeviceRequest)
    
    
}



