#' Cloud User Accounts API Objects 
#' Creates and manages users and groups for accessing Google Compute Engine virtual machines.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 19:35:34
#' filename: /Users/mark/dev/R/autoGoogleAPI/googleclouduseraccountsvmbeta.auto/R/clouduseraccounts_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' AuthorizedKeysView Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A list of authorized public keys for a user account.
#' 
#' @param keys [Output Only] The list of authorized public keys in SSH format
#' @param sudoer [Output Only] Whether the user has the ability to elevate on the instance that requested the authorized keys
#' 
#' @return AuthorizedKeysView object
#' 
#' @family AuthorizedKeysView functions
#' @export
AuthorizedKeysView <- function(keys = NULL, sudoer = NULL) {
    structure(list(keys = keys, sudoer = sudoer), class = "gar_AuthorizedKeysView")
}

#' Group Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Group resource.
#' 
#' @param creationTimestamp [Output Only] Creation timestamp in RFC3339 text format
#' @param description An optional textual description of the resource; provided by the client when the resource is created
#' @param id [Output Only] Unique identifier for the resource; defined by the server
#' @param members [Output Only] A list of URLs to User resources who belong to the group
#' @param name Name of the resource; provided by the client when the resource is created
#' @param selfLink [Output Only] Server defined URL for the resource
#' 
#' @return Group object
#' 
#' @family Group functions
#' @export
Group <- function(creationTimestamp = NULL, description = NULL, id = NULL, members = NULL, 
    name = NULL, selfLink = NULL) {
    structure(list(creationTimestamp = creationTimestamp, description = description, 
        id = id, kind = `clouduseraccounts#group`, members = members, name = name, 
        selfLink = selfLink), class = "gar_Group")
}

#' GroupList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param id [Output Only] Unique identifier for the resource; defined by the server
#' @param items [Output Only] A list of Group resources
#' @param nextPageToken [Output Only] A token used to continue a truncated list request
#' @param selfLink [Output Only] Server defined URL for this resource
#' 
#' @return GroupList object
#' 
#' @family GroupList functions
#' @export
GroupList <- function(id = NULL, items = NULL, nextPageToken = NULL, selfLink = NULL) {
    structure(list(id = id, items = items, kind = `clouduseraccounts#groupList`, 
        nextPageToken = nextPageToken, selfLink = selfLink), class = "gar_GroupList")
}

#' GroupsAddMemberRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param users Fully-qualified URLs of the User resources to add
#' 
#' @return GroupsAddMemberRequest object
#' 
#' @family GroupsAddMemberRequest functions
#' @export
GroupsAddMemberRequest <- function(users = NULL) {
    structure(list(users = users), class = "gar_GroupsAddMemberRequest")
}

#' GroupsRemoveMemberRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param users Fully-qualified URLs of the User resources to remove
#' 
#' @return GroupsRemoveMemberRequest object
#' 
#' @family GroupsRemoveMemberRequest functions
#' @export
GroupsRemoveMemberRequest <- function(users = NULL) {
    structure(list(users = users), class = "gar_GroupsRemoveMemberRequest")
}

#' LinuxAccountViews Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A list of all Linux accounts for this project. This API is only used by Compute Engine virtual machines to get information about user accounts for a project or instance. Linux resources are read-only views into users and groups managed by the Compute Engine Accounts API.
#' 
#' @param groupViews [Output Only] A list of all groups within a project
#' @param userViews [Output Only] A list of all users within a project
#' 
#' @return LinuxAccountViews object
#' 
#' @family LinuxAccountViews functions
#' @export
LinuxAccountViews <- function(groupViews = NULL, userViews = NULL) {
    structure(list(groupViews = groupViews, kind = `clouduseraccounts#linuxAccountViews`, 
        userViews = userViews), class = "gar_LinuxAccountViews")
}

#' LinuxGetAuthorizedKeysViewResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param resource [Output Only] A list of authorized public keys for a user
#' 
#' @return LinuxGetAuthorizedKeysViewResponse object
#' 
#' @family LinuxGetAuthorizedKeysViewResponse functions
#' @export
LinuxGetAuthorizedKeysViewResponse <- function(resource = NULL) {
    structure(list(resource = resource), class = "gar_LinuxGetAuthorizedKeysViewResponse")
}

#' LinuxGetLinuxAccountViewsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param resource [Output Only] A list of authorized user accounts and groups
#' 
#' @return LinuxGetLinuxAccountViewsResponse object
#' 
#' @family LinuxGetLinuxAccountViewsResponse functions
#' @export
LinuxGetLinuxAccountViewsResponse <- function(resource = NULL) {
    structure(list(resource = resource), class = "gar_LinuxGetLinuxAccountViewsResponse")
}

#' LinuxGroupView Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A detailed view of a Linux group.
#' 
#' @param gid [Output Only] The Group ID
#' @param groupName [Output Only] Group name
#' @param members [Output Only] List of user accounts that belong to the group
#' 
#' @return LinuxGroupView object
#' 
#' @family LinuxGroupView functions
#' @export
LinuxGroupView <- function(gid = NULL, groupName = NULL, members = NULL) {
    structure(list(gid = gid, groupName = groupName, members = members), class = "gar_LinuxGroupView")
}

#' LinuxUserView Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A detailed view of a Linux user account.
#' 
#' @param gecos [Output Only] The GECOS (user information) entry for this account
#' @param gid [Output Only] User's default group ID
#' @param homeDirectory [Output Only] The path to the home directory for this account
#' @param shell [Output Only] The path to the login shell for this account
#' @param uid [Output Only] User ID
#' @param username [Output Only] The username of the account
#' 
#' @return LinuxUserView object
#' 
#' @family LinuxUserView functions
#' @export
LinuxUserView <- function(gecos = NULL, gid = NULL, homeDirectory = NULL, shell = NULL, 
    uid = NULL, username = NULL) {
    structure(list(gecos = gecos, gid = gid, homeDirectory = homeDirectory, shell = shell, 
        uid = uid, username = username), class = "gar_LinuxUserView")
}

#' Operation Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' An Operation resource, used to manage asynchronous API requests.
#' 
#' @param Operation.error The \link{Operation.error} object or list of objects
#' @param Operation.error.errors The \link{Operation.error.errors} object or list of objects
#' @param Operation.warnings The \link{Operation.warnings} object or list of objects
#' @param Operation.warnings.data The \link{Operation.warnings.data} object or list of objects
#' @param clientOperationId [Output Only] Reserved for future use
#' @param creationTimestamp [Output Only] Creation timestamp in RFC3339 text format
#' @param description [Output Only] A textual description of the operation, which is set when the operation is created
#' @param endTime [Output Only] The time that this operation was completed
#' @param error [Output Only] If errors are generated during processing of the operation, this field will be populated
#' @param httpErrorMessage [Output Only] If the operation fails, this field contains the HTTP error message that was returned, such as NOT FOUND
#' @param httpErrorStatusCode [Output Only] If the operation fails, this field contains the HTTP error status code that was returned
#' @param id [Output Only] The unique identifier for the resource
#' @param insertTime [Output Only] The time that this operation was requested
#' @param name [Output Only] Name of the resource
#' @param operationType [Output Only] The type of operation, such as insert, update, or delete, and so on
#' @param progress [Output Only] An optional progress indicator that ranges from 0 to 100
#' @param region [Output Only] The URL of the region where the operation resides
#' @param selfLink [Output Only] Server-defined URL for the resource
#' @param startTime [Output Only] The time that this operation was started by the server
#' @param status [Output Only] The status of the operation, which can be one of the following: PENDING, RUNNING, or DONE
#' @param statusMessage [Output Only] An optional textual description of the current status of the operation
#' @param targetId [Output Only] The unique target ID, which identifies a specific incarnation of the target resource
#' @param targetLink [Output Only] The URL of the resource that the operation modifies
#' @param user [Output Only] User who requested the operation, for example: user@example
#' @param warnings [Output Only] If warning messages are generated during processing of the operation, this field will be populated
#' @param zone [Output Only] The URL of the zone where the operation resides
#' 
#' @return Operation object
#' 
#' @family Operation functions
#' @export
Operation <- function(Operation.error = NULL, Operation.error.errors = NULL, Operation.warnings = NULL, 
    Operation.warnings.data = NULL, clientOperationId = NULL, creationTimestamp = NULL, 
    description = NULL, endTime = NULL, error = NULL, httpErrorMessage = NULL, httpErrorStatusCode = NULL, 
    id = NULL, insertTime = NULL, name = NULL, operationType = NULL, progress = NULL, 
    region = NULL, selfLink = NULL, startTime = NULL, status = NULL, statusMessage = NULL, 
    targetId = NULL, targetLink = NULL, user = NULL, warnings = NULL, zone = NULL) {
    structure(list(Operation.error = Operation.error, Operation.error.errors = Operation.error.errors, 
        Operation.warnings = Operation.warnings, Operation.warnings.data = Operation.warnings.data, 
        clientOperationId = clientOperationId, creationTimestamp = creationTimestamp, 
        description = description, endTime = endTime, error = error, httpErrorMessage = httpErrorMessage, 
        httpErrorStatusCode = httpErrorStatusCode, id = id, insertTime = insertTime, 
        kind = `clouduseraccounts#operation`, name = name, operationType = operationType, 
        progress = progress, region = region, selfLink = selfLink, startTime = startTime, 
        status = status, statusMessage = statusMessage, targetId = targetId, targetLink = targetLink, 
        user = user, warnings = warnings, zone = zone), class = "gar_Operation")
}

#' Operation.error Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' [Output Only] If errors are generated during processing of the operation, this field will be populated.
#' 
#' @param Operation.error.errors The \link{Operation.error.errors} object or list of objects
#' @param errors [Output Only] The array of errors encountered while processing this operation
#' 
#' @return Operation.error object
#' 
#' @family Operation functions
#' @export
Operation.error <- function(Operation.error.errors = NULL, errors = NULL) {
    structure(list(Operation.error.errors = Operation.error.errors, errors = errors), 
        class = "gar_Operation.error")
}

#' Operation.error.errors Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return Operation.error.errors object
#' 
#' @family Operation functions
#' @export
Operation.error.errors <- function() {
    list()
}

#' Operation.warnings Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param Operation.warnings.data The \link{Operation.warnings.data} object or list of objects
#' 
#' @return Operation.warnings object
#' 
#' @family Operation functions
#' @export
Operation.warnings <- function(Operation.warnings.data = NULL) {
    structure(list(Operation.warnings.data = Operation.warnings.data), class = "gar_Operation.warnings")
}

#' Operation.warnings.data Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return Operation.warnings.data object
#' 
#' @family Operation functions
#' @export
Operation.warnings.data <- function() {
    list()
}

#' OperationList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Contains a list of Operation resources.
#' 
#' @param id [Output Only] The unique identifier for the resource
#' @param items [Output Only] A list of Operation resources
#' @param nextPageToken [Output Only] This token allows you to get the next page of results for list requests
#' @param selfLink [Output Only] Server-defined URL for this resource
#' 
#' @return OperationList object
#' 
#' @family OperationList functions
#' @export
OperationList <- function(id = NULL, items = NULL, nextPageToken = NULL, selfLink = NULL) {
    structure(list(id = id, items = items, kind = `clouduseraccounts#operationList`, 
        nextPageToken = nextPageToken, selfLink = selfLink), class = "gar_OperationList")
}

#' PublicKey Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A public key for authenticating to guests.
#' 
#' @param creationTimestamp [Output Only] Creation timestamp in RFC3339 text format
#' @param description An optional textual description of the resource; provided by the client when the resource is created
#' @param expirationTimestamp Optional expiration timestamp
#' @param fingerprint [Output Only] The fingerprint of the key is defined by RFC4716 to be the MD5 digest of the public key
#' @param key Public key text in SSH format, defined by RFC4253 section 6
#' 
#' @return PublicKey object
#' 
#' @family PublicKey functions
#' @export
PublicKey <- function(creationTimestamp = NULL, description = NULL, expirationTimestamp = NULL, 
    fingerprint = NULL, key = NULL) {
    structure(list(creationTimestamp = creationTimestamp, description = description, 
        expirationTimestamp = expirationTimestamp, fingerprint = fingerprint, key = key), 
        class = "gar_PublicKey")
}

#' User Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A User resource.
#' 
#' @param creationTimestamp [Output Only] Creation timestamp in RFC3339 text format
#' @param description An optional textual description of the resource; provided by the client when the resource is created
#' @param groups [Output Only] A list of URLs to Group resources who contain the user
#' @param id [Output Only] Unique identifier for the resource; defined by the server
#' @param name Name of the resource; provided by the client when the resource is created
#' @param owner Email address of account's owner
#' @param publicKeys [Output Only] Public keys that this user may use to login
#' @param selfLink [Output Only] Server defined URL for the resource
#' 
#' @return User object
#' 
#' @family User functions
#' @export
User <- function(creationTimestamp = NULL, description = NULL, groups = NULL, id = NULL, 
    name = NULL, owner = NULL, publicKeys = NULL, selfLink = NULL) {
    structure(list(creationTimestamp = creationTimestamp, description = description, 
        groups = groups, id = id, kind = `clouduseraccounts#user`, name = name, owner = owner, 
        publicKeys = publicKeys, selfLink = selfLink), class = "gar_User")
}


#' UserList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param id [Output Only] Unique identifier for the resource; defined by the server
#' @param items [Output Only] A list of User resources
#' @param nextPageToken [Output Only] A token used to continue a truncated list request
#' @param selfLink [Output Only] Server defined URL for this resource
#' 
#' @return UserList object
#' 
#' @family UserList functions
#' @export


UserList <- function(id = NULL, items = NULL, nextPageToken = NULL, selfLink = NULL) {
    
    
    
    structure(list(id = id, items = items, kind = `clouduseraccounts#userList`, nextPageToken = nextPageToken, 
        selfLink = selfLink), class = "gar_UserList")
}

