#' Google Cloud Trace API
#' Send and retrieve trace data from Google Cloud Trace. Data is generated and available by default for all App Engine applications. Data from other applications can be written to Cloud Trace for display, reporting, and analysis.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2016-09-03 23:17:45
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlecloudtracev1.auto/R/cloudtrace_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/trace.append
#' \item https://www.googleapis.com/auth/trace.readonly
#' }
#' 
#' @docType package 
#' @name cloudtrace_googleAuthR
#' 
NULL
## NULL



#' Sends new traces to Stackdriver Trace or updates existing traces. If the ID of a trace that you send matches that of an existing trace, any fields in the existing trace and its spans are overwritten by the provided values, and any new fields provided are merged with the existing trace data. If the ID does not match, a new trace is created.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/tools/cloud-trace}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/trace.append
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/trace.append)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Traces The \link{Traces} object to pass to this method
#' @param projectId ID of the Cloud project where the trace data is stored
#' @importFrom googleAuthR gar_api_generator
#' @family Traces functions
#' @export


projects.patchTraces <- function(Traces, projectId) {
    
    
    url <- sprintf("https://cloudtrace.googleapis.com/v1/projects/%s/traces", projectId)
    # cloudtrace.projects.patchTraces
    f <- gar_api_generator(url, "PATCH", data_parse_function = function(x) x)
    
    stopifnot(inherits(Traces, "gar_Traces"))
    
    f(the_body = Traces)
    
    
}



