#' Google Cloud DNS API
#' Configures and serves authoritative DNS records.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 19:48:17
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlednsv2beta1.auto/R/dns_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' @docType package 
#' @name dns_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Atomically update the ResourceRecordSet collection.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Change The \link{Change} object to pass to this method
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @family Change functions
#' @export
changes.create <- function(Change, project, managedZone, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/changes", 
        project, managedZone)
    # dns.changes.create
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Change, "gar_Change"))
    
    f(the_body = Change)
    
}

#' Fetch the representation of an existing Change.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param changeId The identifier of the requested change, from a previous ResourceRecordSetsChangeResponse
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @export
changes.get <- function(project, managedZone, changeId, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/changes/%s", 
        project, managedZone, changeId)
    # dns.changes.get
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Enumerate Changes to a ResourceRecordSet collection.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param maxResults Optional
#' @param pageToken Optional
#' @param sortBy Sorting criterion
#' @param sortOrder Sorting order direction: 'ascending' or 'descending'
#' @importFrom googleAuthR gar_api_generator
#' @export
changes.list <- function(project, managedZone, maxResults = NULL, pageToken = NULL, 
    sortBy = NULL, sortOrder = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/changes", 
        project, managedZone)
    # dns.changes.list
    pars = list(maxResults = maxResults, pageToken = pageToken, sortBy = sortBy, 
        sortOrder = sortOrder)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Fetch the representation of an existing DnsKey.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param dnsKeyId The identifier of the requested DnsKey
#' @param clientOperationId For mutating operation requests only
#' @param digestType An optional comma-separated list of digest types to compute and display for key signing keys
#' @importFrom googleAuthR gar_api_generator
#' @export
eys.get <- function(project, managedZone, dnsKeyId, clientOperationId = NULL, digestType = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/dnsKeys/%s", 
        project, managedZone, dnsKeyId)
    # dns.dnsKeys.get
    pars = list(clientOperationId = clientOperationId, digestType = digestType)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Enumerate DnsKeys to a ResourceRecordSet collection.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param digestType An optional comma-separated list of digest types to compute and display for key signing keys
#' @param maxResults Optional
#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
eys.list <- function(project, managedZone, digestType = NULL, maxResults = NULL, 
    pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/dnsKeys", 
        project, managedZone)
    # dns.dnsKeys.list
    pars = list(digestType = digestType, maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Fetch the representation of an existing Operation.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param operation Identifies the operation addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @export
managedZoneOperations.get <- function(project, managedZone, operation, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/operations/%s", 
        project, managedZone, operation)
    # dns.managedZoneOperations.get
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Enumerate Operations for the given ManagedZone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param maxResults Optional
#' @param pageToken Optional
#' @param sortBy Sorting criterion
#' @importFrom googleAuthR gar_api_generator
#' @export
managedZoneOperations.list <- function(project, managedZone, maxResults = NULL, pageToken = NULL, 
    sortBy = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/operations", 
        project, managedZone)
    # dns.managedZoneOperations.list
    pars = list(maxResults = maxResults, pageToken = pageToken, sortBy = sortBy)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Create a new ManagedZone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ManagedZone The \link{ManagedZone} object to pass to this method
#' @param project Identifies the project addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @family ManagedZone functions
#' @export
managedZones.create <- function(ManagedZone, project, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones", 
        project)
    # dns.managedZones.create
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ManagedZone, "gar_ManagedZone"))
    
    f(the_body = ManagedZone)
    
}

#' Delete a previously created ManagedZone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @export
managedZones.delete <- function(project, managedZone, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s", 
        project, managedZone)
    # dns.managedZones.delete
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Fetch the representation of an existing ManagedZone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @export
managedZones.get <- function(project, managedZone, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s", 
        project, managedZone)
    # dns.managedZones.get
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Enumerate ManagedZones that have been created but not yet deleted.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param dnsName Restricts the list to return only zones with this domain name
#' @param maxResults Optional
#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
managedZones.list <- function(project, dnsName = NULL, maxResults = NULL, pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones", 
        project)
    # dns.managedZones.list
    pars = list(dnsName = dnsName, maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Update an existing ManagedZone. This method supports patch semantics.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ManagedZone The \link{ManagedZone} object to pass to this method
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @family ManagedZone functions
#' @export
managedZones.patch <- function(ManagedZone, project, managedZone, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s", 
        project, managedZone)
    # dns.managedZones.patch
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ManagedZone, "gar_ManagedZone"))
    
    f(the_body = ManagedZone)
    
}

#' Update an existing ManagedZone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ManagedZone The \link{ManagedZone} object to pass to this method
#' @param project Identifies the project addressed by this request
#' @param managedZone Identifies the managed zone addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @family ManagedZone functions
#' @export
managedZones.update <- function(ManagedZone, project, managedZone, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s", 
        project, managedZone)
    # dns.managedZones.update
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "PUT", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ManagedZone, "gar_ManagedZone"))
    
    f(the_body = ManagedZone)
    
}

#' Fetch the representation of an existing Project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request
#' @param clientOperationId For mutating operation requests only
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.get <- function(project, clientOperationId = NULL) {
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s", project)
    # dns.projects.get
    pars = list(clientOperationId = clientOperationId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}


#' Enumerate ResourceRecordSets that have been created but not yet deleted.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/cloud-dns}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/ndev.clouddns.readonly
#' \item https://www.googleapis.com/auth/ndev.clouddns.readwrite
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/ndev.clouddns.readonly, https://www.googleapis.com/auth/ndev.clouddns.readwrite)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Identifies the project addressed by this request

#' @param managedZone Identifies the managed zone addressed by this request

#' @param maxResults Optional

#' @param name Restricts the list to return only records with this fully qualified domain name

#' @param pageToken Optional

#' @param type Restricts the list to return only records of this type
#' @importFrom googleAuthR gar_api_generator
#' @export


resourceRecordSets.list <- function(project, managedZone, maxResults = NULL, name = NULL, 
    pageToken = NULL, type = NULL) {
    
    
    url <- sprintf("https://www.googleapis.com/dns/v2beta1/projects/%s/managedZones/%s/rrsets", 
        project, managedZone)
    # dns.resourceRecordSets.list
    pars = list(maxResults = maxResults, name = name, pageToken = pageToken, type = type)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    f()
    
    
}



