#' Cloud Monitoring API
#' Accesses Google Cloud Monitoring data.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 19:32:52
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlecloudmonitoringv2beta2.auto/R/cloudmonitoring_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' @docType package 
#' @name cloudmonitoring_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Create a new metric.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param MetricDescriptor The \link{MetricDescriptor} object to pass to this method
#' @param project The project id
#' @importFrom googleAuthR gar_api_generator
#' @family MetricDescriptor functions
#' @export
metricDescriptors.create <- function(MetricDescriptor, project) {
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/metricDescriptors", 
        project)
    # cloudmonitoring.metricDescriptors.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(MetricDescriptor, "gar_MetricDescriptor"))
    
    f(the_body = MetricDescriptor)
    
}

#' Delete an existing metric.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The project ID to which the metric belongs
#' @param metric Name of the metric
#' @importFrom googleAuthR gar_api_generator
#' @export
metricDescriptors.delete <- function(project, metric) {
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/metricDescriptors/%s", 
        project, metric)
    # cloudmonitoring.metricDescriptors.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' List metric descriptors that match the query. If the query is not set, then all of the metric descriptors will be returned. Large responses will be paginated, use the nextPageToken returned in the response to request subsequent pages of results by setting the pageToken query parameter to the value of the nextPageToken.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ListMetricDescriptorsRequest The \link{ListMetricDescriptorsRequest} object to pass to this method
#' @param project The project id
#' @param count Maximum number of metric descriptors per page
#' @param pageToken The pagination token, which is used to page through large result sets
#' @param query The query used to search against existing metrics
#' @importFrom googleAuthR gar_api_generator
#' @family ListMetricDescriptorsRequest functions
#' @export
metricDescriptors.list <- function(ListMetricDescriptorsRequest, project, count = NULL, 
    pageToken = NULL, query = NULL) {
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/metricDescriptors", 
        project)
    # cloudmonitoring.metricDescriptors.list
    pars = list(count = count, pageToken = pageToken, query = query)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ListMetricDescriptorsRequest, "gar_ListMetricDescriptorsRequest"))
    
    f(the_body = ListMetricDescriptorsRequest)
    
}

#' List the data points of the time series that match the metric and labels values and that have data points in the interval. Large responses are paginated; use the nextPageToken returned in the response to request subsequent pages of results by setting the pageToken query parameter to the value of the nextPageToken.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ListTimeseriesRequest The \link{ListTimeseriesRequest} object to pass to this method
#' @param project The project ID to which this time series belongs
#' @param metric Metric names are protocol-free URLs as listed in the Supported Metrics page
#' @param youngest End of the time interval (inclusive), which is expressed as an RFC 3339 timestamp
#' @param aggregator The aggregation function that will reduce the data points in each window to a single point
#' @param count Maximum number of data points per page, which is used for pagination of results
#' @param labels A collection of labels for the matching time series, which are represented as:  
#' @param oldest Start of the time interval (exclusive), which is expressed as an RFC 3339 timestamp
#' @param pageToken The pagination token, which is used to page through large result sets
#' @param timespan Length of the time interval to query, which is an alternative way to declare the interval: (youngest - timespan, youngest]
#' @param window The sampling window
#' @importFrom googleAuthR gar_api_generator
#' @family ListTimeseriesRequest functions
#' @export
timeseries.list <- function(ListTimeseriesRequest, project, metric, youngest, aggregator = NULL, 
    count = NULL, labels = NULL, oldest = NULL, pageToken = NULL, timespan = NULL, 
    window = NULL) {
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/timeseries/%s", 
        project, metric)
    # cloudmonitoring.timeseries.list
    pars = list(youngest = youngest, aggregator = aggregator, count = count, labels = labels, 
        oldest = oldest, pageToken = pageToken, timespan = timespan, window = window)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ListTimeseriesRequest, "gar_ListTimeseriesRequest"))
    
    f(the_body = ListTimeseriesRequest)
    
}

#' Put data points to one or more time series for one or more metrics. If a time series does not exist, a new time series will be created. It is not allowed to write a time series point that is older than the existing youngest point of that time series. Points that are older than the existing youngest point of that time series will be discarded silently. Therefore, users should make sure that points of a time series are written sequentially in the order of their end time.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param WriteTimeseriesRequest The \link{WriteTimeseriesRequest} object to pass to this method
#' @param project The project ID
#' @importFrom googleAuthR gar_api_generator
#' @family WriteTimeseriesRequest functions
#' @export
timeseries.write <- function(WriteTimeseriesRequest, project) {
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/timeseries:write", 
        project)
    # cloudmonitoring.timeseries.write
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(WriteTimeseriesRequest, "gar_WriteTimeseriesRequest"))
    
    f(the_body = WriteTimeseriesRequest)
    
}


#' List the descriptors of the time series that match the metric and labels values and that have data points in the interval. Large responses are paginated; use the nextPageToken returned in the response to request subsequent pages of results by setting the pageToken query parameter to the value of the nextPageToken.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/monitoring/v2beta2/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/monitoring
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/monitoring)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ListTimeseriesDescriptorsRequest The \link{ListTimeseriesDescriptorsRequest} object to pass to this method
#' @param project The project ID to which this time series belongs

#' @param metric Metric names are protocol-free URLs as listed in the Supported Metrics page

#' @param youngest End of the time interval (inclusive), which is expressed as an RFC 3339 timestamp

#' @param aggregator The aggregation function that will reduce the data points in each window to a single point

#' @param count Maximum number of time series descriptors per page

#' @param labels A collection of labels for the matching time series, which are represented as:  

#' @param oldest Start of the time interval (exclusive), which is expressed as an RFC 3339 timestamp

#' @param pageToken The pagination token, which is used to page through large result sets

#' @param timespan Length of the time interval to query, which is an alternative way to declare the interval: (youngest - timespan, youngest]

#' @param window The sampling window
#' @importFrom googleAuthR gar_api_generator
#' @family ListTimeseriesDescriptorsRequest functions
#' @export


timeseriesDescriptors.list <- function(ListTimeseriesDescriptorsRequest, project, 
    metric, youngest, aggregator = NULL, count = NULL, labels = NULL, oldest = NULL, 
    pageToken = NULL, timespan = NULL, window = NULL) {
    
    
    url <- sprintf("https://www.googleapis.com/cloudmonitoring/v2beta2/projects/%s/timeseriesDescriptors/%s", 
        project, metric)
    # cloudmonitoring.timeseriesDescriptors.list
    pars = list(youngest = youngest, aggregator = aggregator, count = count, labels = labels, 
        oldest = oldest, pageToken = pageToken, timespan = timespan, window = window)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    stopifnot(inherits(ListTimeseriesDescriptorsRequest, "gar_ListTimeseriesDescriptorsRequest"))
    
    f(the_body = ListTimeseriesDescriptorsRequest)
    
    
}



