#' Google Compute Engine Instance Group Updater API
#' [Deprecated. Please use compute.instanceGroupManagers.update method. replicapoolupdater API will be disabled after December 30th, 2016] Updates groups of Compute Engine instances.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 20:09:30
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlereplicapoolupdaterv1beta1.auto/R/replicapoolupdater_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/replicapool
#' \item https://www.googleapis.com/auth/replicapool.readonly
#' }
#' 
#' @docType package 
#' @name replicapoolupdater_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.cancel <- function(project, zone, rollingUpdate) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s/cancel", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()
    
}

#' Returns information about an update.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/replicapool
#' \item https://www.googleapis.com/auth/replicapool.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/replicapool, https://www.googleapis.com/auth/replicapool.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.get <- function(project, zone, rollingUpdate) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Inserts and starts a new update.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param RollingUpdate The \link{RollingUpdate} object to pass to this method
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @importFrom googleAuthR gar_api_generator
#' @family RollingUpdate functions
#' @export
rollingUpdates.insert <- function(RollingUpdate, project, zone) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates", 
        project, zone)
    # replicapoolupdater.rollingUpdates.insert
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(RollingUpdate, "gar_RollingUpdate"))
    
    f(the_body = RollingUpdate)
    
}

#' Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/replicapool
#' \item https://www.googleapis.com/auth/replicapool.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/replicapool, https://www.googleapis.com/auth/replicapool.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param filter Optional
#' @param maxResults Optional
#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.list <- function(project, zone, filter = NULL, maxResults = NULL, 
    pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates", 
        project, zone)
    # replicapoolupdater.rollingUpdates.list
    pars = list(filter = filter, maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Lists the current status for each instance within a given update.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' \item https://www.googleapis.com/auth/replicapool
#' \item https://www.googleapis.com/auth/replicapool.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only, https://www.googleapis.com/auth/replicapool, https://www.googleapis.com/auth/replicapool.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @param filter Optional
#' @param maxResults Optional
#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.listInstanceUpdates <- function(project, zone, rollingUpdate, filter = NULL, 
    maxResults = NULL, pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s/instanceUpdates", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.listInstanceUpdates
    pars = list(filter = filter, maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.pause <- function(project, zone, rollingUpdate) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s/pause", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.pause
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()
    
}

#' Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.resume <- function(project, zone, rollingUpdate) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s/resume", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.resume
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()
    
}

#' Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The Google Developers Console project name
#' @param zone The name of the zone in which the update's target resides
#' @param rollingUpdate The name of the update
#' @importFrom googleAuthR gar_api_generator
#' @export
rollingUpdates.rollback <- function(project, zone, rollingUpdate) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/rollingUpdates/%s/rollback", 
        project, zone, rollingUpdate)
    # replicapoolupdater.rollingUpdates.rollback
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()
    
}

#' Retrieves the specified zone-specific operation resource.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Name of the project scoping this request
#' @param zone Name of the zone scoping this request
#' @param operation Name of the operation resource to return
#' @importFrom googleAuthR gar_api_generator
#' @export
zoneOperations.get <- function(project, zone, operation) {
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/operations/%s", 
        project, zone, operation)
    # replicapoolupdater.zoneOperations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}


#' Retrieves the list of Operation resources contained within the specified zone.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/replicapool
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/replicapool)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project Name of the project scoping this request

#' @param zone Name of the zone scoping this request

#' @param filter Optional

#' @param maxResults Optional

#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export


zoneOperations.list <- function(project, zone, filter = NULL, maxResults = NULL, 
    pageToken = NULL) {
    
    
    url <- sprintf("https://www.googleapis.com/replicapoolupdater/v1beta1/projects/%s/zones/%s/operations", 
        project, zone)
    # replicapoolupdater.zoneOperations.list
    pars = list(filter = filter, maxResults = maxResults, pageToken = pageToken)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    f()
    
    
}



