#' Google Cloud Pub/Sub API Objects 
#' Provides reliable, many-to-many, asynchronous messaging between applications.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2016-09-03 23:22:16
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlepubsubv1.auto/R/pubsub_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' SetIamPolicyRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request message for `SetIamPolicy` method.
#' 
#' @param policy REQUIRED: The complete policy to be applied to the `resource`
#' 
#' @return SetIamPolicyRequest object
#' 
#' @family SetIamPolicyRequest functions
#' @export
SetIamPolicyRequest <- function(policy = NULL) {
    structure(list(policy = policy), class = "gar_SetIamPolicyRequest")
}

#' Policy Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Defines an Identity and Access Management (IAM) policy. It is used to specify access control policies for Cloud Platform resources. A `Policy` consists of a list of `bindings`. A `Binding` binds a list of `members` to a `role`, where the members can be user accounts, Google groups, Google domains, and service accounts. A `role` is a named list of permissions defined by IAM. **Example** { 'bindings': [ { 'role': 'roles/owner', 'members': [ 'user:mike@example.com', 'group:admins@example.com', 'domain:google.com', 'serviceAccount:my-other-app@appspot.gserviceaccount.com', ] }, { 'role': 'roles/viewer', 'members': ['user:sean@example.com'] } ] } For a description of IAM and its features, see the [IAM developer's guide](https://cloud.google.com/iam).
#' 
#' @param version Version of the `Policy`
#' @param bindings Associates a list of `members` to a `role`
#' @param etag `etag` is used for optimistic concurrency control as a way to help prevent simultaneous updates of a policy from overwriting each other
#' 
#' @return Policy object
#' 
#' @family Policy functions
#' @export
Policy <- function(version = NULL, bindings = NULL, etag = NULL) {
    structure(list(version = version, bindings = bindings, etag = etag), class = "gar_Policy")
}

#' Binding Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Associates `members` with a `role`.
#' 
#' @param role Role that is assigned to `members`
#' @param members Specifies the identities requesting access for a Cloud Platform resource
#' 
#' @return Binding object
#' 
#' @family Binding functions
#' @export
Binding <- function(role = NULL, members = NULL) {
    structure(list(role = role, members = members), class = "gar_Binding")
}

#' TestIamPermissionsRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request message for `TestIamPermissions` method.
#' 
#' @param permissions The set of permissions to check for the `resource`
#' 
#' @return TestIamPermissionsRequest object
#' 
#' @family TestIamPermissionsRequest functions
#' @export
TestIamPermissionsRequest <- function(permissions = NULL) {
    structure(list(permissions = permissions), class = "gar_TestIamPermissionsRequest")
}

#' TestIamPermissionsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for `TestIamPermissions` method.
#' 
#' @param permissions A subset of `TestPermissionsRequest
#' 
#' @return TestIamPermissionsResponse object
#' 
#' @family TestIamPermissionsResponse functions
#' @export
TestIamPermissionsResponse <- function(permissions = NULL) {
    structure(list(permissions = permissions), class = "gar_TestIamPermissionsResponse")
}

#' Topic Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A topic resource.
#' 
#' @param name The name of the topic
#' 
#' @return Topic object
#' 
#' @family Topic functions
#' @export
Topic <- function(name = NULL) {
    structure(list(name = name), class = "gar_Topic")
}

#' PublishRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request for the Publish method.
#' 
#' @param messages The messages to publish
#' 
#' @return PublishRequest object
#' 
#' @family PublishRequest functions
#' @export
PublishRequest <- function(messages = NULL) {
    structure(list(messages = messages), class = "gar_PublishRequest")
}

#' PubsubMessage Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A message data and its attributes. The message payload must not be empty; it must contain either a non-empty data field, or at least one attribute.
#' 
#' @param PubsubMessage.attributes The \link{PubsubMessage.attributes} object or list of objects
#' @param data The message payload
#' @param attributes Optional attributes for this message
#' @param messageId ID of this message, assigned by the server when the message is published
#' @param publishTime The time at which the message was published, populated by the server when it receives the `Publish` call
#' 
#' @return PubsubMessage object
#' 
#' @family PubsubMessage functions
#' @export
PubsubMessage <- function(PubsubMessage.attributes = NULL, data = NULL, attributes = NULL, 
    messageId = NULL, publishTime = NULL) {
    structure(list(PubsubMessage.attributes = PubsubMessage.attributes, data = data, 
        attributes = attributes, messageId = messageId, publishTime = publishTime), 
        class = "gar_PubsubMessage")
}

#' PubsubMessage.attributes Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Optional attributes for this message.
#' 
#' 
#' 
#' @return PubsubMessage.attributes object
#' 
#' @family PubsubMessage functions
#' @export
PubsubMessage.attributes <- function() {
    list()
}

#' PublishResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response for the `Publish` method.
#' 
#' @param messageIds The server-assigned ID of each published message, in the same order as the messages in the request
#' 
#' @return PublishResponse object
#' 
#' @family PublishResponse functions
#' @export
PublishResponse <- function(messageIds = NULL) {
    structure(list(messageIds = messageIds), class = "gar_PublishResponse")
}

#' ListTopicsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response for the `ListTopics` method.
#' 
#' @param topics The resulting topics
#' @param nextPageToken If not empty, indicates that there may be more topics that match the request; this value should be passed in a new `ListTopicsRequest`
#' 
#' @return ListTopicsResponse object
#' 
#' @family ListTopicsResponse functions
#' @export
ListTopicsResponse <- function(topics = NULL, nextPageToken = NULL) {
    structure(list(topics = topics, nextPageToken = nextPageToken), class = "gar_ListTopicsResponse")
}

#' ListTopicSubscriptionsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response for the `ListTopicSubscriptions` method.
#' 
#' @param subscriptions The names of the subscriptions that match the request
#' @param nextPageToken If not empty, indicates that there may be more subscriptions that match the request; this value should be passed in a new `ListTopicSubscriptionsRequest` to get more subscriptions
#' 
#' @return ListTopicSubscriptionsResponse object
#' 
#' @family ListTopicSubscriptionsResponse functions
#' @export
ListTopicSubscriptionsResponse <- function(subscriptions = NULL, nextPageToken = NULL) {
    structure(list(subscriptions = subscriptions, nextPageToken = nextPageToken), 
        class = "gar_ListTopicSubscriptionsResponse")
}

#' Empty Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); } The JSON representation for `Empty` is empty JSON object `{}`.
#' 
#' 
#' 
#' @return Empty object
#' 
#' @family Empty functions
#' @export
Empty <- function() {
    list()
}

#' Subscription Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A subscription resource.
#' 
#' @param name The name of the subscription
#' @param topic The name of the topic from which this subscription is receiving messages
#' @param pushConfig If push delivery is used with this subscription, this field is used to configure it
#' @param ackDeadlineSeconds This value is the maximum time after a subscriber receives a message before the subscriber should acknowledge the message
#' 
#' @return Subscription object
#' 
#' @family Subscription functions
#' @export
Subscription <- function(name = NULL, topic = NULL, pushConfig = NULL, ackDeadlineSeconds = NULL) {
    structure(list(name = name, topic = topic, pushConfig = pushConfig, ackDeadlineSeconds = ackDeadlineSeconds), 
        class = "gar_Subscription")
}

#' PushConfig Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Configuration for a push delivery endpoint.
#' 
#' @param PushConfig.attributes The \link{PushConfig.attributes} object or list of objects
#' @param pushEndpoint A URL locating the endpoint to which messages should be pushed
#' @param attributes Endpoint configuration attributes
#' 
#' @return PushConfig object
#' 
#' @family PushConfig functions
#' @export
PushConfig <- function(PushConfig.attributes = NULL, pushEndpoint = NULL, attributes = NULL) {
    structure(list(PushConfig.attributes = PushConfig.attributes, pushEndpoint = pushEndpoint, 
        attributes = attributes), class = "gar_PushConfig")
}

#' PushConfig.attributes Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Endpoint configuration attributes. Every endpoint has a set of API supported attributes that can be used to control different aspects of the message delivery. The currently supported attribute is `x-goog-version`, which you can use to change the format of the push message. This attribute indicates the version of the data expected by the endpoint. This controls the shape of the envelope (i.e. its fields and metadata). The endpoint version is based on the version of the Pub/Sub API. If not present during the `CreateSubscription` call, it will default to the version of the API used to make such call. If not present during a `ModifyPushConfig` call, its value will not be changed. `GetSubscription` calls will always return a valid version, even if the subscription was created without this attribute. The possible values for this attribute are: * `v1beta1`: uses the push format defined in the v1beta1 Pub/Sub API. * `v1` or `v1beta2`: uses the push format defined in the v1 Pub/Sub API.
#' 
#' 
#' 
#' @return PushConfig.attributes object
#' 
#' @family PushConfig functions
#' @export
PushConfig.attributes <- function() {
    list()
}

#' ListSubscriptionsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response for the `ListSubscriptions` method.
#' 
#' @param subscriptions The subscriptions that match the request
#' @param nextPageToken If not empty, indicates that there may be more subscriptions that match the request; this value should be passed in a new `ListSubscriptionsRequest` to get more subscriptions
#' 
#' @return ListSubscriptionsResponse object
#' 
#' @family ListSubscriptionsResponse functions
#' @export
ListSubscriptionsResponse <- function(subscriptions = NULL, nextPageToken = NULL) {
    structure(list(subscriptions = subscriptions, nextPageToken = nextPageToken), 
        class = "gar_ListSubscriptionsResponse")
}

#' ModifyAckDeadlineRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request for the ModifyAckDeadline method.
#' 
#' @param ackIds List of acknowledgment IDs
#' @param ackDeadlineSeconds The new ack deadline with respect to the time this request was sent to the Pub/Sub system
#' 
#' @return ModifyAckDeadlineRequest object
#' 
#' @family ModifyAckDeadlineRequest functions
#' @export
ModifyAckDeadlineRequest <- function(ackIds = NULL, ackDeadlineSeconds = NULL) {
    structure(list(ackIds = ackIds, ackDeadlineSeconds = ackDeadlineSeconds), class = "gar_ModifyAckDeadlineRequest")
}

#' AcknowledgeRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request for the Acknowledge method.
#' 
#' @param ackIds The acknowledgment ID for the messages being acknowledged that was returned by the Pub/Sub system in the `Pull` response
#' 
#' @return AcknowledgeRequest object
#' 
#' @family AcknowledgeRequest functions
#' @export
AcknowledgeRequest <- function(ackIds = NULL) {
    structure(list(ackIds = ackIds), class = "gar_AcknowledgeRequest")
}

#' PullRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request for the `Pull` method.
#' 
#' @param returnImmediately If this is specified as true the system will respond immediately even if it is not able to return a message in the `Pull` response
#' @param maxMessages The maximum number of messages returned for this request
#' 
#' @return PullRequest object
#' 
#' @family PullRequest functions
#' @export
PullRequest <- function(returnImmediately = NULL, maxMessages = NULL) {
    structure(list(returnImmediately = returnImmediately, maxMessages = maxMessages), 
        class = "gar_PullRequest")
}

#' PullResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response for the `Pull` method.
#' 
#' @param receivedMessages Received Pub/Sub messages
#' 
#' @return PullResponse object
#' 
#' @family PullResponse functions
#' @export
PullResponse <- function(receivedMessages = NULL) {
    structure(list(receivedMessages = receivedMessages), class = "gar_PullResponse")
}

#' ReceivedMessage Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A message and its corresponding acknowledgment ID.
#' 
#' @param ackId This ID can be used to acknowledge the received message
#' @param message The message
#' 
#' @return ReceivedMessage object
#' 
#' @family ReceivedMessage functions
#' @export
ReceivedMessage <- function(ackId = NULL, message = NULL) {
    structure(list(ackId = ackId, message = message), class = "gar_ReceivedMessage")
}


#' ModifyPushConfigRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request for the ModifyPushConfig method.
#' 
#' @param pushConfig The push configuration for future deliveries
#' 
#' @return ModifyPushConfigRequest object
#' 
#' @family ModifyPushConfigRequest functions
#' @export


ModifyPushConfigRequest <- function(pushConfig = NULL) {
    
    
    
    structure(list(pushConfig = pushConfig), class = "gar_ModifyPushConfigRequest")
}

