#' Knowledge Graph Search API
#' Searches the Google Knowledge Graph for entities.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 19:59:51
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlekgsearchv1.auto/R/kgsearch_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item 
#' }
#' 
#' @docType package 
#' @name kgsearch_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}


#' Searches Knowledge Graph for entities that match the constraints.A list of matched entities will be returned in response, which will be inJSON-LD format and compatible with http://schema.org
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/knowledge-graph/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item 
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c()}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param prefix Enables prefix match against names and aliases of entities

#' @param query The literal query string for search

#' @param types Restricts returned entities with these types, e

#' @param indent Enables indenting of json results

#' @param languages The list of language codes (defined in ISO 693) to run the query with,

#' @param ids The list of entity id to be used for search instead of query string

#' @param limit Limits the number of entities to be returned
#' @importFrom googleAuthR gar_api_generator
#' @export


entities.search <- function(prefix = NULL, query = NULL, types = NULL, indent = NULL, 
    languages = NULL, ids = NULL, limit = NULL) {
    
    
    url <- "https://kgsearch.googleapis.com/v1/entities:search"
    # kgsearch.entities.search
    pars = list(prefix = prefix, query = query, types = types, indent = indent, languages = languages, 
        ids = ids, limit = limit)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    f()
    
    
}



