#' Google Cloud Machine Learning Engine
#' An API to enable creating and using machine learning models.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 20:02:30
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlemlv1beta1.auto/R/ml_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' @docType package 
#' @name ml_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Performs prediction on the data in the request.**** REMOVE FROM GENERATED DOCUMENTATION
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1beta1__PredictRequest The \link{GoogleCloudMlV1beta1__PredictRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1beta1__PredictRequest functions
#' @export
projects.predict <- function(GoogleCloudMlV1beta1__PredictRequest, name) {
    url <- sprintf("https://ml.googleapis.com/v1beta1/{+name}:predict", name)
    # ml.projects.predict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1beta1__PredictRequest, "gar_GoogleCloudMlV1beta1__PredictRequest"))
    
    f(the_body = GoogleCloudMlV1beta1__PredictRequest)
    
}


#' Get the service account information associated with your project. You needthis information in order to grant the service account persmissions forthe Google Cloud Storage location where you put your model training codefor training the model with Google Cloud Machine Learning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export


projects.getConfig <- function(name) {
    
    
    url <- sprintf("https://ml.googleapis.com/v1beta1/{+name}:getConfig", name)
    # ml.projects.getConfig
    
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    
    f()
    
    
}



