#' Groups Migration API
#' Groups Migration Api.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2016-09-03 23:15:13
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlegroupsmigrationv1.auto/R/groupsmigration_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/apps.groups.migration
#' }
#' 
#' @docType package 
#' @name groupsmigration_googleAuthR
#' 
NULL
## NULL



#' Inserts a new mail into the archive of the Google group.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/google-apps/groups-migration/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/apps.groups.migration
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/apps.groups.migration)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param groupId The group ID
#' @importFrom googleAuthR gar_api_generator
#' @export


archive.insert <- function(groupId) {
    
    
    url <- sprintf("https://www.googleapis.com/groups/v1/groups/%s/archive", groupId)
    # groupsmigration.archive.insert
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    
    f()
    
    
}



