#' AdSense Host API Objects 
#' Generates performance reports, generates ad codes, and provides publisher management capabilities for AdSense Hosts.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 19:24:20
#' filename: /Users/mark/dev/R/autoGoogleAPI/googleadsensehostv41.auto/R/adsensehost_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Account Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param id Unique identifier of this account
#' @param name Name of this account
#' @param status Approval status of this account
#' 
#' @return Account object
#' 
#' @family Account functions
#' @export
Account <- function(id = NULL, name = NULL, status = NULL) {
    structure(list(id = id, kind = `adsensehost#account`, name = name, status = status), 
        class = "gar_Account")
}

#' Accounts Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag ETag of this response for caching purposes
#' @param items The accounts returned in this list response
#' 
#' @return Accounts object
#' 
#' @family Accounts functions
#' @export
Accounts <- function(etag = NULL, items = NULL) {
    structure(list(etag = etag, items = items, kind = `adsensehost#accounts`), class = "gar_Accounts")
}

#' AdClient Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param arcOptIn Whether this ad client is opted in to ARC
#' @param id Unique identifier of this ad client
#' @param productCode This ad client's product code, which corresponds to the PRODUCT_CODE report dimension
#' @param supportsReporting Whether this ad client supports being reported on
#' 
#' @return AdClient object
#' 
#' @family AdClient functions
#' @export
AdClient <- function(arcOptIn = NULL, id = NULL, productCode = NULL, supportsReporting = NULL) {
    structure(list(arcOptIn = arcOptIn, id = id, kind = `adsensehost#adClient`, productCode = productCode, 
        supportsReporting = supportsReporting), class = "gar_AdClient")
}

#' AdClients Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag ETag of this response for caching purposes
#' @param items The ad clients returned in this list response
#' @param nextPageToken Continuation token used to page through ad clients
#' 
#' @return AdClients object
#' 
#' @family AdClients functions
#' @export
AdClients <- function(etag = NULL, items = NULL, nextPageToken = NULL) {
    structure(list(etag = etag, items = items, kind = `adsensehost#adClients`, nextPageToken = nextPageToken), 
        class = "gar_AdClients")
}

#' AdCode Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param adCode The ad code snippet
#' 
#' @return AdCode object
#' 
#' @family AdCode functions
#' @export
AdCode <- function(adCode = NULL) {
    structure(list(adCode = adCode, kind = `adsensehost#adCode`), class = "gar_AdCode")
}

#' AdStyle Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param AdStyle.colors The \link{AdStyle.colors} object or list of objects
#' @param AdStyle.font The \link{AdStyle.font} object or list of objects
#' @param colors The colors included in the style
#' @param corners The style of the corners in the ad (deprecated: never populated, ignored)
#' @param font The font which is included in the style
#' 
#' @return AdStyle object
#' 
#' @family AdStyle functions
#' @export
AdStyle <- function(AdStyle.colors = NULL, AdStyle.font = NULL, colors = NULL, corners = NULL, 
    font = NULL) {
    structure(list(AdStyle.colors = AdStyle.colors, AdStyle.font = AdStyle.font, 
        colors = colors, corners = corners, font = font, kind = `adsensehost#adStyle`), 
        class = "gar_AdStyle")
}

#' AdStyle.colors Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The colors included in the style. These are represented as six hexadecimal characters, similar to HTML color codes, but without the leading hash.
#' 
#' @param background The color of the ad background
#' @param border The color of the ad border
#' @param text The color of the ad text
#' @param title The color of the ad title
#' @param url The color of the ad url
#' 
#' @return AdStyle.colors object
#' 
#' @family AdStyle functions
#' @export
AdStyle.colors <- function(background = NULL, border = NULL, text = NULL, title = NULL, 
    url = NULL) {
    structure(list(background = background, border = border, text = text, title = title, 
        url = url), class = "gar_AdStyle.colors")
}

#' AdStyle.font Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The font which is included in the style.
#' 
#' @param family The family of the font
#' @param size The size of the font
#' 
#' @return AdStyle.font object
#' 
#' @family AdStyle functions
#' @export
AdStyle.font <- function(family = NULL, size = NULL) {
    structure(list(family = family, size = size), class = "gar_AdStyle.font")
}

#' AdUnit Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param AdUnit.contentAdsSettings The \link{AdUnit.contentAdsSettings} object or list of objects
#' @param AdUnit.contentAdsSettings.backupOption The \link{AdUnit.contentAdsSettings.backupOption} object or list of objects
#' @param AdUnit.mobileContentAdsSettings The \link{AdUnit.mobileContentAdsSettings} object or list of objects
#' @param code Identity code of this ad unit, not necessarily unique across ad clients
#' @param contentAdsSettings Settings specific to content ads (AFC) and highend mobile content ads (AFMC - deprecated)
#' @param customStyle Custom style information specific to this ad unit
#' @param id Unique identifier of this ad unit
#' @param mobileContentAdsSettings Settings specific to WAP mobile content ads (AFMC - deprecated)
#' @param name Name of this ad unit
#' @param status Status of this ad unit
#' 
#' @return AdUnit object
#' 
#' @family AdUnit functions
#' @export
AdUnit <- function(AdUnit.contentAdsSettings = NULL, AdUnit.contentAdsSettings.backupOption = NULL, 
    AdUnit.mobileContentAdsSettings = NULL, code = NULL, contentAdsSettings = NULL, 
    customStyle = NULL, id = NULL, mobileContentAdsSettings = NULL, name = NULL, 
    status = NULL) {
    structure(list(AdUnit.contentAdsSettings = AdUnit.contentAdsSettings, AdUnit.contentAdsSettings.backupOption = AdUnit.contentAdsSettings.backupOption, 
        AdUnit.mobileContentAdsSettings = AdUnit.mobileContentAdsSettings, code = code, 
        contentAdsSettings = contentAdsSettings, customStyle = customStyle, id = id, 
        kind = `adsensehost#adUnit`, mobileContentAdsSettings = mobileContentAdsSettings, 
        name = name, status = status), class = "gar_AdUnit")
}

#' AdUnit.contentAdsSettings Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Settings specific to content ads (AFC) and highend mobile content ads (AFMC - deprecated).
#' 
#' @param AdUnit.contentAdsSettings.backupOption The \link{AdUnit.contentAdsSettings.backupOption} object or list of objects
#' @param backupOption The backup option to be used in instances where no ad is available
#' @param size Size of this ad unit
#' @param type Type of this ad unit
#' 
#' @return AdUnit.contentAdsSettings object
#' 
#' @family AdUnit functions
#' @export
AdUnit.contentAdsSettings <- function(AdUnit.contentAdsSettings.backupOption = NULL, 
    backupOption = NULL, size = NULL, type = NULL) {
    structure(list(AdUnit.contentAdsSettings.backupOption = AdUnit.contentAdsSettings.backupOption, 
        backupOption = backupOption, size = size, type = type), class = "gar_AdUnit.contentAdsSettings")
}

#' AdUnit.contentAdsSettings.backupOption Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The backup option to be used in instances where no ad is available.
#' 
#' @param color Color to use when type is set to COLOR
#' @param type Type of the backup option
#' @param url URL to use when type is set to URL
#' 
#' @return AdUnit.contentAdsSettings.backupOption object
#' 
#' @family AdUnit functions
#' @export
AdUnit.contentAdsSettings.backupOption <- function(color = NULL, type = NULL, url = NULL) {
    structure(list(color = color, type = type, url = url), class = "gar_AdUnit.contentAdsSettings.backupOption")
}

#' AdUnit.mobileContentAdsSettings Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Settings specific to WAP mobile content ads (AFMC - deprecated).
#' 
#' @param markupLanguage The markup language to use for this ad unit
#' @param scriptingLanguage The scripting language to use for this ad unit
#' @param size Size of this ad unit
#' @param type Type of this ad unit
#' 
#' @return AdUnit.mobileContentAdsSettings object
#' 
#' @family AdUnit functions
#' @export
AdUnit.mobileContentAdsSettings <- function(markupLanguage = NULL, scriptingLanguage = NULL, 
    size = NULL, type = NULL) {
    structure(list(markupLanguage = markupLanguage, scriptingLanguage = scriptingLanguage, 
        size = size, type = type), class = "gar_AdUnit.mobileContentAdsSettings")
}

#' AdUnits Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag ETag of this response for caching purposes
#' @param items The ad units returned in this list response
#' @param nextPageToken Continuation token used to page through ad units
#' 
#' @return AdUnits object
#' 
#' @family AdUnits functions
#' @export
AdUnits <- function(etag = NULL, items = NULL, nextPageToken = NULL) {
    structure(list(etag = etag, items = items, kind = `adsensehost#adUnits`, nextPageToken = nextPageToken), 
        class = "gar_AdUnits")
}

#' AssociationSession Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param accountId Hosted account id of the associated publisher after association
#' @param id Unique identifier of this association session
#' @param productCodes The products to associate with the user
#' @param redirectUrl Redirect URL of this association session
#' @param status Status of the completed association, available once the association callback token has been verified
#' @param userLocale The preferred locale of the user themselves when going through the AdSense association flow
#' @param websiteLocale The locale of the user's hosted website
#' @param websiteUrl The URL of the user's hosted website
#' 
#' @return AssociationSession object
#' 
#' @family AssociationSession functions
#' @export
AssociationSession <- function(accountId = NULL, id = NULL, productCodes = NULL, 
    redirectUrl = NULL, status = NULL, userLocale = NULL, websiteLocale = NULL, websiteUrl = NULL) {
    structure(list(accountId = accountId, id = id, kind = `adsensehost#associationSession`, 
        productCodes = productCodes, redirectUrl = redirectUrl, status = status, 
        userLocale = userLocale, websiteLocale = websiteLocale, websiteUrl = websiteUrl), 
        class = "gar_AssociationSession")
}

#' CustomChannel Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param code Code of this custom channel, not necessarily unique across ad clients
#' @param id Unique identifier of this custom channel
#' @param name Name of this custom channel
#' 
#' @return CustomChannel object
#' 
#' @family CustomChannel functions
#' @export
CustomChannel <- function(code = NULL, id = NULL, name = NULL) {
    structure(list(code = code, id = id, kind = `adsensehost#customChannel`, name = name), 
        class = "gar_CustomChannel")
}

#' CustomChannels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag ETag of this response for caching purposes
#' @param items The custom channels returned in this list response
#' @param nextPageToken Continuation token used to page through custom channels
#' 
#' @return CustomChannels object
#' 
#' @family CustomChannels functions
#' @export
CustomChannels <- function(etag = NULL, items = NULL, nextPageToken = NULL) {
    structure(list(etag = etag, items = items, kind = `adsensehost#customChannels`, 
        nextPageToken = nextPageToken), class = "gar_CustomChannels")
}

#' Report Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param Report.headers The \link{Report.headers} object or list of objects
#' @param averages The averages of the report
#' @param headers The header information of the columns requested in the report
#' @param rows The output rows of the report
#' @param totalMatchedRows The total number of rows matched by the report request
#' @param totals The totals of the report
#' @param warnings Any warnings associated with generation of the report
#' 
#' @return Report object
#' 
#' @family Report functions
#' @export
Report <- function(Report.headers = NULL, averages = NULL, headers = NULL, rows = NULL, 
    totalMatchedRows = NULL, totals = NULL, warnings = NULL) {
    structure(list(Report.headers = Report.headers, averages = averages, headers = headers, 
        kind = `adsensehost#report`, rows = rows, totalMatchedRows = totalMatchedRows, 
        totals = totals, warnings = warnings), class = "gar_Report")
}

#' Report.headers Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return Report.headers object
#' 
#' @family Report functions
#' @export
Report.headers <- function() {
    list()
}

#' UrlChannel Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param id Unique identifier of this URL channel
#' @param urlPattern URL Pattern of this URL channel
#' 
#' @return UrlChannel object
#' 
#' @family UrlChannel functions
#' @export
UrlChannel <- function(id = NULL, urlPattern = NULL) {
    structure(list(id = id, kind = `adsensehost#urlChannel`, urlPattern = urlPattern), 
        class = "gar_UrlChannel")
}


#' UrlChannels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag ETag of this response for caching purposes
#' @param items The URL channels returned in this list response
#' @param nextPageToken Continuation token used to page through URL channels
#' 
#' @return UrlChannels object
#' 
#' @family UrlChannels functions
#' @export


UrlChannels <- function(etag = NULL, items = NULL, nextPageToken = NULL) {
    
    
    
    structure(list(etag = etag, items = items, kind = `adsensehost#urlChannels`, 
        nextPageToken = nextPageToken), class = "gar_UrlChannels")
}

