#' Google Search Console URL Testing Tools API Objects 
#' Provides tools for running validation tests against single URLs
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 20:11:59
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlesearchconsolev1.auto/R/searchconsole_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' MobileFriendlyIssue Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Mobile-friendly issue.
#' 
#' @param rule Rule violated
#' 
#' @return MobileFriendlyIssue object
#' 
#' @family MobileFriendlyIssue functions
#' @export
MobileFriendlyIssue <- function(rule = NULL) {
    structure(list(rule = rule), class = "gar_MobileFriendlyIssue")
}

#' RunMobileFriendlyTestResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Mobile-friendly test response, including mobile-friendly issues and resourceissues.
#' 
#' @param mobileFriendliness Test verdict, whether the page is mobile friendly or not
#' @param mobileFriendlyIssues List of mobile-usability issues
#' @param screenshot Screenshot of the requested URL
#' @param testStatus Final state of the test, can be either complete or an error
#' @param resourceIssues Information about embedded resources issues
#' 
#' @return RunMobileFriendlyTestResponse object
#' 
#' @family RunMobileFriendlyTestResponse functions
#' @export
RunMobileFriendlyTestResponse <- function(mobileFriendliness = NULL, mobileFriendlyIssues = NULL, 
    screenshot = NULL, testStatus = NULL, resourceIssues = NULL) {
    structure(list(mobileFriendliness = mobileFriendliness, mobileFriendlyIssues = mobileFriendlyIssues, 
        screenshot = screenshot, testStatus = testStatus, resourceIssues = resourceIssues), 
        class = "gar_RunMobileFriendlyTestResponse")
}

#' ResourceIssue Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Information about a resource with issue.
#' 
#' @param blockedResource Describes a blocked resource issue
#' 
#' @return ResourceIssue object
#' 
#' @family ResourceIssue functions
#' @export
ResourceIssue <- function(blockedResource = NULL) {
    structure(list(blockedResource = blockedResource), class = "gar_ResourceIssue")
}

#' BlockedResource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Blocked resource.
#' 
#' @param url URL of the blocked resource
#' 
#' @return BlockedResource object
#' 
#' @family BlockedResource functions
#' @export
BlockedResource <- function(url = NULL) {
    structure(list(url = url), class = "gar_BlockedResource")
}

#' TestStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Final state of the test, including error details if necessary.
#' 
#' @param status Status of the test
#' @param details Error details if applicable
#' 
#' @return TestStatus object
#' 
#' @family TestStatus functions
#' @export
TestStatus <- function(status = NULL, details = NULL) {
    structure(list(status = status, details = details), class = "gar_TestStatus")
}

#' RunMobileFriendlyTestRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Mobile-friendly test request.
#' 
#' @param requestScreenshot Whether or not screenshot is requested
#' @param url URL for inspection
#' 
#' @return RunMobileFriendlyTestRequest object
#' 
#' @family RunMobileFriendlyTestRequest functions
#' @export
RunMobileFriendlyTestRequest <- function(requestScreenshot = NULL, url = NULL) {
    structure(list(requestScreenshot = requestScreenshot, url = url), class = "gar_RunMobileFriendlyTestRequest")
}


#' Image Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Describe image data.
#' 
#' @param mimeType The mime-type of the image data
#' @param data Image data in format determined by the mime type
#' 
#' @return Image object
#' 
#' @family Image functions
#' @export


Image <- function(mimeType = NULL, data = NULL) {
    
    
    
    structure(list(mimeType = mimeType, data = data), class = "gar_Image")
}

