#' URL Shortener API Objects 
#' Lets you create, inspect, and manage goo.gl short URLs
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 20:21:27
#' filename: /Users/mark/dev/R/autoGoogleAPI/googleurlshortenerv1.auto/R/urlshortener_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' AnalyticsSnapshot Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param browsers Top browsers, e
#' @param countries Top countries (expressed as country codes), e
#' @param longUrlClicks Number of clicks on all goo
#' @param platforms Top platforms or OSes, e
#' @param referrers Top referring hosts, e
#' @param shortUrlClicks Number of clicks on this short URL
#' 
#' @return AnalyticsSnapshot object
#' 
#' @family AnalyticsSnapshot functions
#' @export
AnalyticsSnapshot <- function(browsers = NULL, countries = NULL, longUrlClicks = NULL, 
    platforms = NULL, referrers = NULL, shortUrlClicks = NULL) {
    structure(list(browsers = browsers, countries = countries, longUrlClicks = longUrlClicks, 
        platforms = platforms, referrers = referrers, shortUrlClicks = shortUrlClicks), 
        class = "gar_AnalyticsSnapshot")
}

#' AnalyticsSummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param allTime Click analytics over all time
#' @param day Click analytics over the last day
#' @param month Click analytics over the last month
#' @param twoHours Click analytics over the last two hours
#' @param week Click analytics over the last week
#' 
#' @return AnalyticsSummary object
#' 
#' @family AnalyticsSummary functions
#' @export
AnalyticsSummary <- function(allTime = NULL, day = NULL, month = NULL, twoHours = NULL, 
    week = NULL) {
    structure(list(allTime = allTime, day = day, month = month, twoHours = twoHours, 
        week = week), class = "gar_AnalyticsSummary")
}

#' StringCount Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param count Number of clicks for this top entry, e
#' @param id Label assigned to this top entry, e
#' 
#' @return StringCount object
#' 
#' @family StringCount functions
#' @export
StringCount <- function(count = NULL, id = NULL) {
    structure(list(count = count, id = id), class = "gar_StringCount")
}

#' Url Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param analytics A summary of the click analytics for the short and long URL
#' @param created Time the short URL was created; ISO 8601 representation using the yyyy-MM-dd'T'HH:mm:ss
#' @param id Short URL, e
#' @param longUrl Long URL, e
#' @param status Status of the target URL
#' 
#' @return Url object
#' 
#' @family Url functions
#' @export
Url <- function(analytics = NULL, created = NULL, id = NULL, longUrl = NULL, status = NULL) {
    structure(list(analytics = analytics, created = created, id = id, kind = `urlshortener#url`, 
        longUrl = longUrl, status = status), class = "gar_Url")
}


#' UrlHistory Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param items A list of URL resources
#' @param itemsPerPage Number of items returned with each full 'page' of results
#' @param nextPageToken A token to provide to get the next page of results
#' @param totalItems Total number of short URLs associated with this user (may be approximate)
#' 
#' @return UrlHistory object
#' 
#' @family UrlHistory functions
#' @export


UrlHistory <- function(items = NULL, itemsPerPage = NULL, nextPageToken = NULL, totalItems = NULL) {
    
    
    
    structure(list(items = items, itemsPerPage = itemsPerPage, kind = `urlshortener#urlHistory`, 
        nextPageToken = nextPageToken, totalItems = totalItems), class = "gar_UrlHistory")
}

