#' Google Fonts Developer API Objects 
#' Accesses the metadata for all families served by Google Fonts, providing a list of families currently available (including available styles and a list of supported script subsets).
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 20:22:03
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlewebfontsv1.auto/R/webfonts_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Webfont Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param Webfont.files The \link{Webfont.files} object or list of objects
#' @param category The category of the font
#' @param family The name of the font
#' @param files The font files (with all supported scripts) for each one of the available variants, as a key : value map
#' @param lastModified The date (format 'yyyy-MM-dd') the font was modified for the last time
#' @param subsets The scripts supported by the font
#' @param variants The available variants for the font
#' @param version The font version
#' 
#' @return Webfont object
#' 
#' @family Webfont functions
#' @export
Webfont <- function(Webfont.files = NULL, category = NULL, family = NULL, files = NULL, 
    lastModified = NULL, subsets = NULL, variants = NULL, version = NULL) {
    structure(list(Webfont.files = Webfont.files, category = category, family = family, 
        files = files, kind = `webfonts#webfont`, lastModified = lastModified, subsets = subsets, 
        variants = variants, version = version), class = "gar_Webfont")
}

#' Webfont.files Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The font files (with all supported scripts) for each one of the available variants, as a key : value map.
#' 
#' 
#' 
#' @return Webfont.files object
#' 
#' @family Webfont functions
#' @export
Webfont.files <- function() {
    list()
}


#' WebfontList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param items The list of fonts currently served by the Google Fonts API
#' 
#' @return WebfontList object
#' 
#' @family WebfontList functions
#' @export


WebfontList <- function(items = NULL) {
    
    
    
    structure(list(items = items, kind = `webfonts#webfontList`), class = "gar_WebfontList")
}

