#' Google People API
#' Provides access to information about profiles and contacts.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 20:04:23
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlepeoplev1.auto/R/people_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/user.emails.read
#' \item https://www.googleapis.com/auth/contacts
#' \item https://www.googleapis.com/auth/user.addresses.read
#' \item https://www.googleapis.com/auth/userinfo.email
#' \item https://www.googleapis.com/auth/user.phonenumbers.read
#' \item https://www.googleapis.com/auth/user.birthday.read
#' \item https://www.googleapis.com/auth/contacts.readonly
#' \item https://www.googleapis.com/auth/plus.login
#' \item https://www.googleapis.com/auth/userinfo.profile
#' }
#' 
#' @docType package 
#' @name people_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Provides information about a list of specific people by specifying a listof requested resource names. Use `people/me` to indicate the authenticateduser.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/people/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/contacts
#' \item https://www.googleapis.com/auth/contacts.readonly
#' \item https://www.googleapis.com/auth/plus.login
#' \item https://www.googleapis.com/auth/user.addresses.read
#' \item https://www.googleapis.com/auth/user.birthday.read
#' \item https://www.googleapis.com/auth/user.emails.read
#' \item https://www.googleapis.com/auth/user.phonenumbers.read
#' \item https://www.googleapis.com/auth/userinfo.email
#' \item https://www.googleapis.com/auth/userinfo.profile
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/contacts, https://www.googleapis.com/auth/contacts.readonly, https://www.googleapis.com/auth/plus.login, https://www.googleapis.com/auth/user.addresses.read, https://www.googleapis.com/auth/user.birthday.read, https://www.googleapis.com/auth/user.emails.read, https://www.googleapis.com/auth/user.phonenumbers.read, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param requestMask.includeField Comma-separated list of fields to be included in the response
#' @param resourceNames The resource name, such as one returned by
#' @importFrom googleAuthR gar_api_generator
#' @export
getBatchGet <- function(requestMask.includeField = NULL, resourceNames = NULL) {
    url <- "https://people.googleapis.com/v1/people:batchGet"
    # people.people.getBatchGet
    pars = list(requestMask.includeField = requestMask.includeField, resourceNames = resourceNames)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}


#' Provides information about a person resource for a resource name. Use`people/me` to indicate the authenticated user.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/people/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/contacts
#' \item https://www.googleapis.com/auth/contacts.readonly
#' \item https://www.googleapis.com/auth/plus.login
#' \item https://www.googleapis.com/auth/user.addresses.read
#' \item https://www.googleapis.com/auth/user.birthday.read
#' \item https://www.googleapis.com/auth/user.emails.read
#' \item https://www.googleapis.com/auth/user.phonenumbers.read
#' \item https://www.googleapis.com/auth/userinfo.email
#' \item https://www.googleapis.com/auth/userinfo.profile
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/contacts, https://www.googleapis.com/auth/contacts.readonly, https://www.googleapis.com/auth/plus.login, https://www.googleapis.com/auth/user.addresses.read, https://www.googleapis.com/auth/user.birthday.read, https://www.googleapis.com/auth/user.emails.read, https://www.googleapis.com/auth/user.phonenumbers.read, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resourceName The resource name of the person to provide information about

#' @param requestMask.includeField Comma-separated list of fields to be included in the response
#' @importFrom googleAuthR gar_api_generator
#' @export


get <- function(resourceName, requestMask.includeField = NULL) {
    
    
    url <- sprintf("https://people.googleapis.com/v1/{+resourceName}", resourceName)
    # people.people.get
    pars = list(requestMask.includeField = requestMask.includeField)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    f()
    
    
}



