#' DoubleClick Bid Manager API Objects 
#' API for viewing and managing your reports in DoubleClick Bid Manager.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2017-03-05 19:48:39
#' filename: /Users/mark/dev/R/autoGoogleAPI/googledoubleclickbidmanagerv1.auto/R/doubleclickbidmanager_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' DownloadLineItemsRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request to fetch stored line items.
#' 
#' @param fileSpec File specification (column names, types, order) in which the line items will be returned
#' @param filterIds Ids of the specified filter type used to filter line items to fetch
#' @param filterType Filter type used to filter line items to fetch
#' @param format Format in which the line items will be returned
#' 
#' @return DownloadLineItemsRequest object
#' 
#' @family DownloadLineItemsRequest functions
#' @export
DownloadLineItemsRequest <- function(fileSpec = NULL, filterIds = NULL, filterType = NULL, 
    format = NULL) {
    structure(list(fileSpec = fileSpec, filterIds = filterIds, filterType = filterType, 
        format = format), class = "gar_DownloadLineItemsRequest")
}

#' DownloadLineItemsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Download line items response.
#' 
#' @param lineItems Retrieved line items in CSV format
#' 
#' @return DownloadLineItemsResponse object
#' 
#' @family DownloadLineItemsResponse functions
#' @export
DownloadLineItemsResponse <- function(lineItems = NULL) {
    structure(list(lineItems = lineItems), class = "gar_DownloadLineItemsResponse")
}

#' DownloadRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request to fetch stored insertion orders, line items, TrueView ad groups and ads.
#' 
#' @param fileTypes File types that will be returned
#' @param filterIds The IDs of the specified filter type
#' @param filterType Filter type used to filter line items to fetch
#' @param version SDF Version (column names, types, order) in which the entities will be returned
#' 
#' @return DownloadRequest object
#' 
#' @family DownloadRequest functions
#' @export
DownloadRequest <- function(fileTypes = NULL, filterIds = NULL, filterType = NULL, 
    version = NULL) {
    structure(list(fileTypes = fileTypes, filterIds = filterIds, filterType = filterType, 
        version = version), class = "gar_DownloadRequest")
}

#' DownloadResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Download response.
#' 
#' @param adGroups Retrieved ad groups in SDF format
#' @param ads Retrieved ads in SDF format
#' @param insertionOrders Retrieved insertion orders in SDF format
#' @param lineItems Retrieved line items in SDF format
#' 
#' @return DownloadResponse object
#' 
#' @family DownloadResponse functions
#' @export
DownloadResponse <- function(adGroups = NULL, ads = NULL, insertionOrders = NULL, 
    lineItems = NULL) {
    structure(list(adGroups = adGroups, ads = ads, insertionOrders = insertionOrders, 
        lineItems = lineItems), class = "gar_DownloadResponse")
}

#' FilterPair Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Filter used to match traffic data in your report.
#' 
#' @param type Filter type
#' @param value Filter value
#' 
#' @return FilterPair object
#' 
#' @family FilterPair functions
#' @export
FilterPair <- function(type = NULL, value = NULL) {
    structure(list(type = type, value = value), class = "gar_FilterPair")
}

#' ListQueriesResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' List queries response.
#' 
#' @param queries Retrieved queries
#' 
#' @return ListQueriesResponse object
#' 
#' @family ListQueriesResponse functions
#' @export
ListQueriesResponse <- function(queries = NULL) {
    structure(list(kind = `doubleclickbidmanager#listQueriesResponse`, queries = queries), 
        class = "gar_ListQueriesResponse")
}

#' ListReportsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' List reports response.
#' 
#' @param reports Retrieved reports
#' 
#' @return ListReportsResponse object
#' 
#' @family ListReportsResponse functions
#' @export
ListReportsResponse <- function(reports = NULL) {
    structure(list(kind = `doubleclickbidmanager#listReportsResponse`, reports = reports), 
        class = "gar_ListReportsResponse")
}

#' Parameters Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Parameters of a query or report.
#' 
#' @param filters Filters used to match traffic data in your report
#' @param groupBys Data is grouped by the filters listed in this field
#' @param includeInviteData Whether to include data from Invite Media
#' @param metrics Metrics to include as columns in your report
#' @param type Report type
#' 
#' @return Parameters object
#' 
#' @family Parameters functions
#' @export
Parameters <- function(filters = NULL, groupBys = NULL, includeInviteData = NULL, 
    metrics = NULL, type = NULL) {
    structure(list(filters = filters, groupBys = groupBys, includeInviteData = includeInviteData, 
        metrics = metrics, type = type), class = "gar_Parameters")
}

#' Query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents a query.
#' 
#' @param metadata Query metadata
#' @param params Query parameters
#' @param queryId Query ID
#' @param reportDataEndTimeMs The ending time for the data that is shown in the report
#' @param reportDataStartTimeMs The starting time for the data that is shown in the report
#' @param schedule Information on how often and when to run a query
#' @param timezoneCode Canonical timezone code for report data time
#' 
#' @return Query object
#' 
#' @family Query functions
#' @export
Query <- function(metadata = NULL, params = NULL, queryId = NULL, reportDataEndTimeMs = NULL, 
    reportDataStartTimeMs = NULL, schedule = NULL, timezoneCode = NULL) {
    structure(list(kind = `doubleclickbidmanager#query`, metadata = metadata, params = params, 
        queryId = queryId, reportDataEndTimeMs = reportDataEndTimeMs, reportDataStartTimeMs = reportDataStartTimeMs, 
        schedule = schedule, timezoneCode = timezoneCode), class = "gar_Query")
}

#' QueryMetadata Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Query metadata.
#' 
#' @param dataRange Range of report data
#' @param format Format of the generated report
#' @param googleCloudStoragePathForLatestReport The path to the location in Google Cloud Storage where the latest report is stored
#' @param googleDrivePathForLatestReport The path in Google Drive for the latest report
#' @param latestReportRunTimeMs The time when the latest report started to run
#' @param locale Locale of the generated reports
#' @param reportCount Number of reports that have been generated for the query
#' @param running Whether the latest report is currently running
#' @param sendNotification Whether to send an email notification when a report is ready
#' @param shareEmailAddress List of email addresses which are sent email notifications when the report is finished
#' @param title Query title
#' 
#' @return QueryMetadata object
#' 
#' @family QueryMetadata functions
#' @export
QueryMetadata <- function(dataRange = NULL, format = NULL, googleCloudStoragePathForLatestReport = NULL, 
    googleDrivePathForLatestReport = NULL, latestReportRunTimeMs = NULL, locale = NULL, 
    reportCount = NULL, running = NULL, sendNotification = NULL, shareEmailAddress = NULL, 
    title = NULL) {
    structure(list(dataRange = dataRange, format = format, googleCloudStoragePathForLatestReport = googleCloudStoragePathForLatestReport, 
        googleDrivePathForLatestReport = googleDrivePathForLatestReport, latestReportRunTimeMs = latestReportRunTimeMs, 
        locale = locale, reportCount = reportCount, running = running, sendNotification = sendNotification, 
        shareEmailAddress = shareEmailAddress, title = title), class = "gar_QueryMetadata")
}

#' QuerySchedule Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Information on how frequently and when to run a query.
#' 
#' @param endTimeMs Datetime to periodically run the query until
#' @param frequency How often the query is run
#' @param nextRunMinuteOfDay Time of day at which a new report will be generated, represented as minutes past midnight
#' @param nextRunTimezoneCode Canonical timezone code for report generation time
#' 
#' @return QuerySchedule object
#' 
#' @family QuerySchedule functions
#' @export
QuerySchedule <- function(endTimeMs = NULL, frequency = NULL, nextRunMinuteOfDay = NULL, 
    nextRunTimezoneCode = NULL) {
    structure(list(endTimeMs = endTimeMs, frequency = frequency, nextRunMinuteOfDay = nextRunMinuteOfDay, 
        nextRunTimezoneCode = nextRunTimezoneCode), class = "gar_QuerySchedule")
}

#' Report Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents a report.
#' 
#' @param key Key used to identify a report
#' @param metadata Report metadata
#' @param params Report parameters
#' 
#' @return Report object
#' 
#' @family Report functions
#' @export
Report <- function(key = NULL, metadata = NULL, params = NULL) {
    structure(list(key = key, metadata = metadata, params = params), class = "gar_Report")
}

#' ReportFailure Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' An explanation of a report failure.
#' 
#' @param errorCode Error code that shows why the report was not created
#' 
#' @return ReportFailure object
#' 
#' @family ReportFailure functions
#' @export
ReportFailure <- function(errorCode = NULL) {
    structure(list(errorCode = errorCode), class = "gar_ReportFailure")
}

#' ReportKey Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Key used to identify a report.
#' 
#' @param queryId Query ID
#' @param reportId Report ID
#' 
#' @return ReportKey object
#' 
#' @family ReportKey functions
#' @export
ReportKey <- function(queryId = NULL, reportId = NULL) {
    structure(list(queryId = queryId, reportId = reportId), class = "gar_ReportKey")
}

#' ReportMetadata Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Report metadata.
#' 
#' @param googleCloudStoragePath The path to the location in Google Cloud Storage where the report is stored
#' @param reportDataEndTimeMs The ending time for the data that is shown in the report
#' @param reportDataStartTimeMs The starting time for the data that is shown in the report
#' @param status Report status
#' 
#' @return ReportMetadata object
#' 
#' @family ReportMetadata functions
#' @export
ReportMetadata <- function(googleCloudStoragePath = NULL, reportDataEndTimeMs = NULL, 
    reportDataStartTimeMs = NULL, status = NULL) {
    structure(list(googleCloudStoragePath = googleCloudStoragePath, reportDataEndTimeMs = reportDataEndTimeMs, 
        reportDataStartTimeMs = reportDataStartTimeMs, status = status), class = "gar_ReportMetadata")
}

#' ReportStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Report status.
#' 
#' @param failure If the report failed, this records the cause
#' @param finishTimeMs The time when this report either completed successfully or failed
#' @param format The file type of the report
#' @param state The state of the report
#' 
#' @return ReportStatus object
#' 
#' @family ReportStatus functions
#' @export
ReportStatus <- function(failure = NULL, finishTimeMs = NULL, format = NULL, state = NULL) {
    structure(list(failure = failure, finishTimeMs = finishTimeMs, format = format, 
        state = state), class = "gar_ReportStatus")
}

#' RowStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents the upload status of a row in the request.
#' 
#' @param changed Whether the stored entity is changed as a result of upload
#' @param entityId Entity Id
#' @param entityName Entity name
#' @param errors Reasons why the entity can't be uploaded
#' @param persisted Whether the entity is persisted
#' @param rowNumber Row number
#' 
#' @return RowStatus object
#' 
#' @family RowStatus functions
#' @export
RowStatus <- function(changed = NULL, entityId = NULL, entityName = NULL, errors = NULL, 
    persisted = NULL, rowNumber = NULL) {
    structure(list(changed = changed, entityId = entityId, entityName = entityName, 
        errors = errors, persisted = persisted, rowNumber = rowNumber), class = "gar_RowStatus")
}

#' RunQueryRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request to run a stored query to generate a report.
#' 
#' @param dataRange Report data range used to generate the report
#' @param reportDataEndTimeMs The ending time for the data that is shown in the report
#' @param reportDataStartTimeMs The starting time for the data that is shown in the report
#' @param timezoneCode Canonical timezone code for report data time
#' 
#' @return RunQueryRequest object
#' 
#' @family RunQueryRequest functions
#' @export
RunQueryRequest <- function(dataRange = NULL, reportDataEndTimeMs = NULL, reportDataStartTimeMs = NULL, 
    timezoneCode = NULL) {
    structure(list(dataRange = dataRange, reportDataEndTimeMs = reportDataEndTimeMs, 
        reportDataStartTimeMs = reportDataStartTimeMs, timezoneCode = timezoneCode), 
        class = "gar_RunQueryRequest")
}

#' UploadLineItemsRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request to upload line items.
#' 
#' @param dryRun Set to true to get upload status without actually persisting the line items
#' @param format Format the line items are in
#' @param lineItems Line items in CSV to upload
#' 
#' @return UploadLineItemsRequest object
#' 
#' @family UploadLineItemsRequest functions
#' @export
UploadLineItemsRequest <- function(dryRun = NULL, format = NULL, lineItems = NULL) {
    structure(list(dryRun = dryRun, format = format, lineItems = lineItems), class = "gar_UploadLineItemsRequest")
}

#' UploadLineItemsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Upload line items response.
#' 
#' @param uploadStatus Status of upload
#' 
#' @return UploadLineItemsResponse object
#' 
#' @family UploadLineItemsResponse functions
#' @export
UploadLineItemsResponse <- function(uploadStatus = NULL) {
    structure(list(uploadStatus = uploadStatus), class = "gar_UploadLineItemsResponse")
}


#' UploadStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents the status of upload.
#' 
#' @param errors Reasons why upload can't be completed
#' @param rowStatus Per-row upload status
#' 
#' @return UploadStatus object
#' 
#' @family UploadStatus functions
#' @export


UploadStatus <- function(errors = NULL, rowStatus = NULL) {
    
    
    
    structure(list(errors = errors, rowStatus = rowStatus), class = "gar_UploadStatus")
}

