#' Google Cloud Pub/Sub API
#' Provides reliable, many-to-many, asynchronous messaging between applications.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 20:08:08
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlepubsubv1beta2.auto/R/pubsub_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' @docType package 
#' @name pubsub_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Gets the access control policy for a resource.Returns an empty policy if the resource exists and does not have a policyset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.topics.getIamPolicy <- function(resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:getIamPolicy", 
        resource)
    # pubsub.projects.topics.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Gets the configuration of a topic.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param topic The name of the topic to get
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.topics.get <- function(topic) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+topic}", topic)
    # pubsub.projects.topics.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Adds one or more messages to the topic. Returns `NOT_FOUND` if the topicdoes not exist. The message payload must not be empty; it must contain either a non-empty data field, or at least one attribute.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PublishRequest The \link{PublishRequest} object to pass to this method
#' @param topic The messages in the request will be published on this topic
#' @importFrom googleAuthR gar_api_generator
#' @family PublishRequest functions
#' @export
projects.topics.publish <- function(PublishRequest, topic) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+topic}:publish", topic)
    # pubsub.projects.topics.publish
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PublishRequest, "gar_PublishRequest"))
    
    f(the_body = PublishRequest)
    
}

#' Returns permissions that a caller has on the specified resource.If the resource does not exist, this will return an empty set ofpermissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-awareUIs and command-line tools, not for authorization checking. This operationmay 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param TestIamPermissionsRequest The \link{TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family TestIamPermissionsRequest functions
#' @export
projects.topics.testIamPermissions <- function(TestIamPermissionsRequest, resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:testIamPermissions", 
        resource)
    # pubsub.projects.topics.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(TestIamPermissionsRequest, "gar_TestIamPermissionsRequest"))
    
    f(the_body = TestIamPermissionsRequest)
    
}

#' Deletes the topic with the given name. Returns `NOT_FOUND` if the topicdoes not exist. After a topic is deleted, a new topic may be created withthe same name; this is an entirely new topic with none of the oldconfiguration or subscriptions. Existing subscriptions to this topic arenot deleted, but their `topic` field is set to `_deleted-topic_`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param topic Name of the topic to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.topics.delete <- function(topic) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+topic}", topic)
    # pubsub.projects.topics.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Lists matching topics.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The name of the cloud project that topics belong to
#' @param pageToken The value returned by the last `ListTopicsResponse`; indicates that this is
#' @param pageSize Maximum number of topics to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.topics.list <- function(project, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+project}/topics", project)
    # pubsub.projects.topics.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces anyexisting policy.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.topics.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:setIamPolicy", 
        resource)
    # pubsub.projects.topics.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Creates the given topic with the given name.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Topic The \link{Topic} object to pass to this method
#' @param name The name of the topic
#' @importFrom googleAuthR gar_api_generator
#' @family Topic functions
#' @export
projects.topics.create <- function(Topic, name) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+name}", name)
    # pubsub.projects.topics.create
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Topic, "gar_Topic"))
    
    f(the_body = Topic)
    
}

#' Returns permissions that a caller has on the specified resource.If the resource does not exist, this will return an empty set ofpermissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-awareUIs and command-line tools, not for authorization checking. This operationmay 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param TestIamPermissionsRequest The \link{TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family TestIamPermissionsRequest functions
#' @export
projects.subscriptions.testIamPermissions <- function(TestIamPermissionsRequest, 
    resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:testIamPermissions", 
        resource)
    # pubsub.projects.subscriptions.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(TestIamPermissionsRequest, "gar_TestIamPermissionsRequest"))
    
    f(the_body = TestIamPermissionsRequest)
    
}

#' Modifies the `PushConfig` for a specified subscription.This may be used to change a push subscription to a pull one (signified byan empty `PushConfig`) or vice versa, or change the endpoint URL and otherattributes of a push subscription. Messages will accumulate for deliverycontinuously through the call regardless of changes to the `PushConfig`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ModifyPushConfigRequest The \link{ModifyPushConfigRequest} object to pass to this method
#' @param subscription The name of the subscription
#' @importFrom googleAuthR gar_api_generator
#' @family ModifyPushConfigRequest functions
#' @export
projects.subscriptions.modifyPushConfig <- function(ModifyPushConfigRequest, subscription) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}:modifyPushConfig", 
        subscription)
    # pubsub.projects.subscriptions.modifyPushConfig
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ModifyPushConfigRequest, "gar_ModifyPushConfigRequest"))
    
    f(the_body = ModifyPushConfigRequest)
    
}

#' Deletes an existing subscription. All pending messages in the subscriptionare immediately dropped. Calls to `Pull` after deletion will return`NOT_FOUND`. After a subscription is deleted, a new one may be created withthe same name, but the new one has no association with the oldsubscription, or its topic unless the same topic is specified.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param subscription The subscription to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.subscriptions.delete <- function(subscription) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}", subscription)
    # pubsub.projects.subscriptions.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Pulls messages from the server. Returns an empty list if there are nomessages available in the backlog. The server may return `UNAVAILABLE` ifthere are too many concurrent pull requests pending for the givensubscription.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PullRequest The \link{PullRequest} object to pass to this method
#' @param subscription The subscription from which messages should be pulled
#' @importFrom googleAuthR gar_api_generator
#' @family PullRequest functions
#' @export
projects.subscriptions.pull <- function(PullRequest, subscription) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}:pull", 
        subscription)
    # pubsub.projects.subscriptions.pull
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PullRequest, "gar_PullRequest"))
    
    f(the_body = PullRequest)
    
}

#' Lists matching subscriptions.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param project The name of the cloud project that subscriptions belong to
#' @param pageToken The value returned by the last `ListSubscriptionsResponse`; indicates that
#' @param pageSize Maximum number of subscriptions to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.subscriptions.list <- function(project, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+project}/subscriptions", 
        project)
    # pubsub.projects.subscriptions.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces anyexisting policy.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.subscriptions.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:setIamPolicy", 
        resource)
    # pubsub.projects.subscriptions.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Creates a subscription to a given topic.If the subscription already exists, returns `ALREADY_EXISTS`.If the corresponding topic doesn't exist, returns `NOT_FOUND`.If the name is not provided in the request, the server will assign a randomname for this subscription on the same project as the topic. Note thatfor REST API requests, you must specify a name.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Subscription The \link{Subscription} object to pass to this method
#' @param name The name of the subscription
#' @importFrom googleAuthR gar_api_generator
#' @family Subscription functions
#' @export
projects.subscriptions.create <- function(Subscription, name) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+name}", name)
    # pubsub.projects.subscriptions.create
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Subscription, "gar_Subscription"))
    
    f(the_body = Subscription)
    
}

#' Acknowledges the messages associated with the `ack_ids` in the`AcknowledgeRequest`. The Pub/Sub system can remove the relevant messagesfrom the subscription.Acknowledging a message whose ack deadline has expired may succeed,but such a message may be redelivered later. Acknowledging a message morethan once will not result in an error.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param AcknowledgeRequest The \link{AcknowledgeRequest} object to pass to this method
#' @param subscription The subscription whose message is being acknowledged
#' @importFrom googleAuthR gar_api_generator
#' @family AcknowledgeRequest functions
#' @export
projects.subscriptions.acknowledge <- function(AcknowledgeRequest, subscription) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}:acknowledge", 
        subscription)
    # pubsub.projects.subscriptions.acknowledge
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(AcknowledgeRequest, "gar_AcknowledgeRequest"))
    
    f(the_body = AcknowledgeRequest)
    
}

#' Modifies the ack deadline for a specific message. This method is usefulto indicate that more time is needed to process a message by thesubscriber, or to make the message available for redelivery if theprocessing was interrupted. Note that this does not modify thesubscription-level `ackDeadlineSeconds` used for subsequent messages.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ModifyAckDeadlineRequest The \link{ModifyAckDeadlineRequest} object to pass to this method
#' @param subscription The name of the subscription
#' @importFrom googleAuthR gar_api_generator
#' @family ModifyAckDeadlineRequest functions
#' @export
projects.subscriptions.modifyAckDeadline <- function(ModifyAckDeadlineRequest, subscription) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}:modifyAckDeadline", 
        subscription)
    # pubsub.projects.subscriptions.modifyAckDeadline
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ModifyAckDeadlineRequest, "gar_ModifyAckDeadlineRequest"))
    
    f(the_body = ModifyAckDeadlineRequest)
    
}

#' Gets the access control policy for a resource.Returns an empty policy if the resource exists and does not have a policyset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.subscriptions.getIamPolicy <- function(resource) {
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+resource}:getIamPolicy", 
        resource)
    # pubsub.projects.subscriptions.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}


#' Gets the configuration details of a subscription.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/pubsub/docs}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/pubsub
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/pubsub)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param subscription The name of the subscription to get
#' @importFrom googleAuthR gar_api_generator
#' @export


projects.subscriptions.get <- function(subscription) {
    
    
    url <- sprintf("https://pubsub.googleapis.com/v1beta2/{+subscription}", subscription)
    # pubsub.projects.subscriptions.get
    
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    
    f()
    
    
}



