#' Google Play Game Services Publishing API
#' The Publishing API for Google Play Game Services.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 19:52:32
#' filename: /Users/mark/dev/R/autoGoogleAPI/googlegamesConfigurationv1configuration.auto/R/gamesConfiguration_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' @docType package 
#' @name gamesConfiguration_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Delete the achievement configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param achievementId The ID of the achievement used by this method
#' @importFrom googleAuthR gar_api_generator
#' @export
achievementConfigurations.delete <- function(achievementId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/achievements/%s", 
        achievementId)
    # gamesConfiguration.achievementConfigurations.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Retrieves the metadata of the achievement configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param achievementId The ID of the achievement used by this method
#' @importFrom googleAuthR gar_api_generator
#' @export
achievementConfigurations.get <- function(achievementId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/achievements/%s", 
        achievementId)
    # gamesConfiguration.achievementConfigurations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Insert a new achievement configuration in this application.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param AchievementConfiguration The \link{AchievementConfiguration} object to pass to this method
#' @param applicationId The application ID from the Google Play developer console
#' @importFrom googleAuthR gar_api_generator
#' @family AchievementConfiguration functions
#' @export
achievementConfigurations.insert <- function(AchievementConfiguration, applicationId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/applications/%s/achievements", 
        applicationId)
    # gamesConfiguration.achievementConfigurations.insert
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(AchievementConfiguration, "gar_AchievementConfiguration"))
    
    f(the_body = AchievementConfiguration)
    
}

#' Returns a list of the achievement configurations in this application.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param applicationId The application ID from the Google Play developer console
#' @param maxResults The maximum number of resource configurations to return in the response, used for paging
#' @param pageToken The token returned by the previous request
#' @importFrom googleAuthR gar_api_generator
#' @export
achievementConfigurations.list <- function(applicationId, maxResults = NULL, pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/applications/%s/achievements", 
        applicationId)
    # gamesConfiguration.achievementConfigurations.list
    pars = list(maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Update the metadata of the achievement configuration with the given ID. This method supports patch semantics.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param AchievementConfiguration The \link{AchievementConfiguration} object to pass to this method
#' @param achievementId The ID of the achievement used by this method
#' @importFrom googleAuthR gar_api_generator
#' @family AchievementConfiguration functions
#' @export
achievementConfigurations.patch <- function(AchievementConfiguration, achievementId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/achievements/%s", 
        achievementId)
    # gamesConfiguration.achievementConfigurations.patch
    f <- googleAuthR::gar_api_generator(url, "PATCH", data_parse_function = function(x) x)
    stopifnot(inherits(AchievementConfiguration, "gar_AchievementConfiguration"))
    
    f(the_body = AchievementConfiguration)
    
}

#' Update the metadata of the achievement configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param AchievementConfiguration The \link{AchievementConfiguration} object to pass to this method
#' @param achievementId The ID of the achievement used by this method
#' @importFrom googleAuthR gar_api_generator
#' @family AchievementConfiguration functions
#' @export
achievementConfigurations.update <- function(AchievementConfiguration, achievementId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/achievements/%s", 
        achievementId)
    # gamesConfiguration.achievementConfigurations.update
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(AchievementConfiguration, "gar_AchievementConfiguration"))
    
    f(the_body = AchievementConfiguration)
    
}

#' Uploads an image for a resource with the given ID and image type.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resourceId The ID of the resource used by this method
#' @param imageType Selects which image in a resource for this method
#' @importFrom googleAuthR gar_api_generator
#' @export
imageConfigurations.upload <- function(resourceId, imageType) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/images/%s/imageType/%s", 
        resourceId, imageType)
    # gamesConfiguration.imageConfigurations.upload
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()
    
}

#' Delete the leaderboard configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param leaderboardId The ID of the leaderboard
#' @importFrom googleAuthR gar_api_generator
#' @export
leaderboardConfigurations.delete <- function(leaderboardId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/leaderboards/%s", 
        leaderboardId)
    # gamesConfiguration.leaderboardConfigurations.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Retrieves the metadata of the leaderboard configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param leaderboardId The ID of the leaderboard
#' @importFrom googleAuthR gar_api_generator
#' @export
leaderboardConfigurations.get <- function(leaderboardId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/leaderboards/%s", 
        leaderboardId)
    # gamesConfiguration.leaderboardConfigurations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Insert a new leaderboard configuration in this application.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param LeaderboardConfiguration The \link{LeaderboardConfiguration} object to pass to this method
#' @param applicationId The application ID from the Google Play developer console
#' @importFrom googleAuthR gar_api_generator
#' @family LeaderboardConfiguration functions
#' @export
leaderboardConfigurations.insert <- function(LeaderboardConfiguration, applicationId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/applications/%s/leaderboards", 
        applicationId)
    # gamesConfiguration.leaderboardConfigurations.insert
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(LeaderboardConfiguration, "gar_LeaderboardConfiguration"))
    
    f(the_body = LeaderboardConfiguration)
    
}

#' Returns a list of the leaderboard configurations in this application.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param applicationId The application ID from the Google Play developer console
#' @param maxResults The maximum number of resource configurations to return in the response, used for paging
#' @param pageToken The token returned by the previous request
#' @importFrom googleAuthR gar_api_generator
#' @export
leaderboardConfigurations.list <- function(applicationId, maxResults = NULL, pageToken = NULL) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/applications/%s/leaderboards", 
        applicationId)
    # gamesConfiguration.leaderboardConfigurations.list
    pars = list(maxResults = maxResults, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Update the metadata of the leaderboard configuration with the given ID. This method supports patch semantics.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param LeaderboardConfiguration The \link{LeaderboardConfiguration} object to pass to this method
#' @param leaderboardId The ID of the leaderboard
#' @importFrom googleAuthR gar_api_generator
#' @family LeaderboardConfiguration functions
#' @export
leaderboardConfigurations.patch <- function(LeaderboardConfiguration, leaderboardId) {
    url <- sprintf("https://www.googleapis.com/games/v1configuration/leaderboards/%s", 
        leaderboardId)
    # gamesConfiguration.leaderboardConfigurations.patch
    f <- googleAuthR::gar_api_generator(url, "PATCH", data_parse_function = function(x) x)
    stopifnot(inherits(LeaderboardConfiguration, "gar_LeaderboardConfiguration"))
    
    f(the_body = LeaderboardConfiguration)
    
}


#' Update the metadata of the leaderboard configuration with the given ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/games/services}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/androidpublisher
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/androidpublisher)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param LeaderboardConfiguration The \link{LeaderboardConfiguration} object to pass to this method
#' @param leaderboardId The ID of the leaderboard
#' @importFrom googleAuthR gar_api_generator
#' @family LeaderboardConfiguration functions
#' @export


leaderboardConfigurations.update <- function(LeaderboardConfiguration, leaderboardId) {
    
    
    url <- sprintf("https://www.googleapis.com/games/v1configuration/leaderboards/%s", 
        leaderboardId)
    # gamesConfiguration.leaderboardConfigurations.update
    
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    
    stopifnot(inherits(LeaderboardConfiguration, "gar_LeaderboardConfiguration"))
    
    f(the_body = LeaderboardConfiguration)
    
    
}



