#' Google Cloud Dataproc API
#' Manages Hadoop-based clusters and jobs on Google Cloud Platform.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2016-09-03 23:19:06
#' filename: /Users/mark/dev/R/autoGoogleAPI/googledataprocv1beta1.auto/R/dataproc_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' @docType package 
#' @name dataproc_googleAuthR
#' 
NULL
## NULL


#' Creates a cluster in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Cluster The \link{Cluster} object to pass to this method
#' @param projectId [Required] The ID of the Google Cloud Platform project that the cluster belongs to
#' @importFrom googleAuthR gar_api_generator
#' @family Cluster functions
#' @export
projects.clusters.create <- function(Cluster, projectId) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters", 
        projectId)
    # dataproc.projects.clusters.create
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Cluster, "gar_Cluster"))
    
    f(the_body = Cluster)
    
}

#' Updates a cluster in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Cluster The \link{Cluster} object to pass to this method
#' @param projectId [Required] The ID of the Google Cloud Platform project the cluster belongs to
#' @param clusterName [Required] The cluster name
#' @param updateMask [Required] Specifies the path, relative to Cluster, of the field to update
#' @importFrom googleAuthR gar_api_generator
#' @family Cluster functions
#' @export
projects.clusters.patch <- function(Cluster, projectId, clusterName, updateMask = NULL) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters/%s", 
        projectId, clusterName)
    # dataproc.projects.clusters.patch
    f <- gar_api_generator(url, "PATCH", pars_args = list(updateMask = updateMask), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Cluster, "gar_Cluster"))
    
    f(the_body = Cluster)
    
}

#' Deletes a cluster in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the cluster belongs to
#' @param clusterName [Required] The cluster name
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.clusters.delete <- function(projectId, clusterName) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters/%s", 
        projectId, clusterName)
    # dataproc.projects.clusters.delete
    f <- gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Gets the resource representation for a cluster in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the cluster belongs to
#' @param clusterName [Required] The cluster name
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.clusters.get <- function(projectId, clusterName) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters/%s", 
        projectId, clusterName)
    # dataproc.projects.clusters.get
    f <- gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Lists all clusters in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the cluster belongs to
#' @param pageSize The standard List page size
#' @param pageToken The standard List page token
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.clusters.list <- function(projectId, pageSize = NULL, pageToken = NULL) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters", 
        projectId)
    # dataproc.projects.clusters.list
    f <- gar_api_generator(url, "GET", pars_args = list(pageSize = pageSize, pageToken = pageToken), 
        data_parse_function = function(x) x)
    f()
    
}

#' Gets cluster diagnostic information. After the operation completes, the Operation.response field contains `DiagnoseClusterOutputLocation`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param DiagnoseClusterRequest The \link{DiagnoseClusterRequest} object to pass to this method
#' @param projectId [Required] The ID of the Google Cloud Platform project that the cluster belongs to
#' @param clusterName [Required] The cluster name
#' @importFrom googleAuthR gar_api_generator
#' @family DiagnoseClusterRequest functions
#' @export
projects.clusters.diagnose <- function(DiagnoseClusterRequest, projectId, clusterName) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/clusters/%s:diagnose", 
        projectId, clusterName)
    # dataproc.projects.clusters.diagnose
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(DiagnoseClusterRequest, "gar_DiagnoseClusterRequest"))
    
    f(the_body = DiagnoseClusterRequest)
    
}

#' Submits a job to a cluster.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SubmitJobRequest The \link{SubmitJobRequest} object to pass to this method
#' @param projectId [Required] The ID of the Google Cloud Platform project that the job belongs to
#' @importFrom googleAuthR gar_api_generator
#' @family SubmitJobRequest functions
#' @export
projects.jobs.submit <- function(SubmitJobRequest, projectId) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/jobs:submit", 
        projectId)
    # dataproc.projects.jobs.submit
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SubmitJobRequest, "gar_SubmitJobRequest"))
    
    f(the_body = SubmitJobRequest)
    
}

#' Gets the resource representation for a job in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the job belongs to
#' @param jobId [Required] The job ID
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.jobs.get <- function(projectId, jobId) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/jobs/%s", 
        projectId, jobId)
    # dataproc.projects.jobs.get
    f <- gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Lists jobs in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the job belongs to
#' @param pageSize [Optional] The number of results to return in each response
#' @param pageToken [Optional] The page token, returned by a previous call, to request the next page of results
#' @param clusterName [Optional] If set, the returned jobs list includes only jobs that were submitted to the named cluster
#' @param jobStateMatcher [Optional] Specifies enumerated categories of jobs to list
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.jobs.list <- function(projectId, pageSize = NULL, pageToken = NULL, clusterName = NULL, 
    jobStateMatcher = NULL) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/jobs", projectId)
    # dataproc.projects.jobs.list
    f <- gar_api_generator(url, "GET", pars_args = list(pageSize = pageSize, pageToken = pageToken, 
        clusterName = clusterName, jobStateMatcher = jobStateMatcher), data_parse_function = function(x) x)
    f()
    
}

#' Starts a job cancellation request. To access the job resource after cancellation, call [jobs.list](/dataproc/reference/rest/v1beta1/projects.jobs/list) or [jobs.get](/dataproc/reference/rest/v1beta1/projects.jobs/get).
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param CancelJobRequest The \link{CancelJobRequest} object to pass to this method
#' @param projectId [Required] The ID of the Google Cloud Platform project that the job belongs to
#' @param jobId [Required] The job ID
#' @importFrom googleAuthR gar_api_generator
#' @family CancelJobRequest functions
#' @export
projects.jobs.cancel <- function(CancelJobRequest, projectId, jobId) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/jobs/%s:cancel", 
        projectId, jobId)
    # dataproc.projects.jobs.cancel
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(CancelJobRequest, "gar_CancelJobRequest"))
    
    f(the_body = CancelJobRequest)
    
}

#' Deletes the job from the project. If the job is active, the delete fails, and the response returns `FAILED_PRECONDITION`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param projectId [Required] The ID of the Google Cloud Platform project that the job belongs to
#' @param jobId [Required] The job ID
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.jobs.delete <- function(projectId, jobId) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/projects/%s/jobs/%s", 
        projectId, jobId)
    # dataproc.projects.jobs.delete
    f <- gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource
#' @importFrom googleAuthR gar_api_generator
#' @export
operations.get <- function(name) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/{+name}", name)
    # dataproc.operations.get
    f <- gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding below allows API services to override the binding to use different resource name schemes, such as `users/*/operations`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation collection
#' @param filter The standard list filter
#' @param pageSize The standard list page size
#' @param pageToken The standard list page token
#' @importFrom googleAuthR gar_api_generator
#' @export
operations.list <- function(name, filter = NULL, pageSize = NULL, pageToken = NULL) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/{+name}", name)
    # dataproc.operations.list
    f <- gar_api_generator(url, "GET", pars_args = list(filter = filter, pageSize = pageSize, 
        pageToken = pageToken), data_parse_function = function(x) x)
    f()
    
}

#' Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use [operations.get](/dataproc/reference/rest/v1beta1/operations/get) or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param CancelOperationRequest The \link{CancelOperationRequest} object to pass to this method
#' @param name The name of the operation resource to be cancelled
#' @importFrom googleAuthR gar_api_generator
#' @family CancelOperationRequest functions
#' @export
operations.cancel <- function(CancelOperationRequest, name) {
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/{+name}:cancel", name)
    # dataproc.operations.cancel
    f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(CancelOperationRequest, "gar_CancelOperationRequest"))
    
    f(the_body = CancelOperationRequest)
    
}


#' Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/dataproc/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource to be deleted
#' @importFrom googleAuthR gar_api_generator
#' @export


operations.delete <- function(name) {
    
    
    url <- sprintf("https://dataproc.googleapis.com/v1beta1/{+name}", name)
    # dataproc.operations.delete
    f <- gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    
    f()
    
    
}



