#' Google Classroom API
#' Manages classes, rosters, and invitations in Google Classroom.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2017-03-05 19:56:19
#' filename: /Users/mark/dev/R/autoGoogleAPI/googleclassroomv1.auto/R/classroom_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.course-work.readonly
#' \item https://www.googleapis.com/auth/classroom.courses
#' \item https://www.googleapis.com/auth/classroom.courses.readonly
#' \item https://www.googleapis.com/auth/classroom.coursework.me
#' \item https://www.googleapis.com/auth/classroom.coursework.me.readonly
#' \item https://www.googleapis.com/auth/classroom.coursework.students
#' \item https://www.googleapis.com/auth/classroom.coursework.students.readonly
#' \item https://www.googleapis.com/auth/classroom.profile.emails
#' \item https://www.googleapis.com/auth/classroom.profile.photos
#' \item https://www.googleapis.com/auth/classroom.rosters
#' \item https://www.googleapis.com/auth/classroom.rosters.readonly
#' \item https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
#' \item https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
#' }
#' 
#' @docType package 
#' @name classroom_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Creates a course. The user specified in `ownerId` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses or for access errors. * `NOT_FOUND` if the primary teacher is not a valid user. * `FAILED_PRECONDITION` if the course owner's account is disabled or for the following request errors: * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if an alias was specified in the `id` and already exists.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Course The \link{Course} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family Course functions
#' @export
courses.create <- function(Course) {
    url <- "https://classroom.googleapis.com/v1/courses"
    # classroom.courses.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Course, "gar_Course"))
    
    f(the_body = Course)
    
}

#' Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' \item https://www.googleapis.com/auth/classroom.courses.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses, https://www.googleapis.com/auth/classroom.courses.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param id Identifier of the course to return
#' @importFrom googleAuthR gar_api_generator
#' @export
courses.get <- function(id) {
    url <- sprintf("https://classroom.googleapis.com/v1/courses/%s", id)
    # classroom.courses.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Course The \link{Course} object to pass to this method
#' @param id Identifier of the course to update
#' @importFrom googleAuthR gar_api_generator
#' @family Course functions
#' @export
courses.update <- function(Course, id) {
    url <- sprintf("https://classroom.googleapis.com/v1/courses/%s", id)
    # classroom.courses.update
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Course, "gar_Course"))
    
    f(the_body = Course)
    
}

#' Updates one or more fields in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Course The \link{Course} object to pass to this method
#' @param id Identifier of the course to update
#' @param updateMask Mask that identifies which fields on the course to update
#' @importFrom googleAuthR gar_api_generator
#' @family Course functions
#' @export
courses.patch <- function(Course, id, updateMask = NULL) {
    url <- sprintf("https://classroom.googleapis.com/v1/courses/%s", id)
    # classroom.courses.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Course, "gar_Course"))
    
    f(the_body = Course)
    
}

#' Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param id Identifier of the course to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
courses.delete <- function(id) {
    url <- sprintf("https://classroom.googleapis.com/v1/courses/%s", id)
    # classroom.courses.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.courses
#' \item https://www.googleapis.com/auth/classroom.courses.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.courses, https://www.googleapis.com/auth/classroom.courses.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param studentId Restricts returned courses to those having a student with the specified identifier
#' @param teacherId Restricts returned courses to those having a teacher with the specified identifier
#' @param courseStates Restricts returned courses to those in one of the specified states
#' @param pageSize Maximum number of items to return
#' @param pageToken nextPageToken value returned from a previous list call, indicating that the subsequent page of results should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
courses.list <- function(studentId = NULL, teacherId = NULL, courseStates = NULL, 
    pageSize = NULL, pageToken = NULL) {
    url <- "https://classroom.googleapis.com/v1/courses"
    # classroom.courses.list
    pars = list(studentId = studentId, teacherId = teacherId, courseStates = courseStates, 
        pageSize = pageSize, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile, if no profile exists with the requested ID, or for access errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.profile.emails
#' \item https://www.googleapis.com/auth/classroom.profile.photos
#' \item https://www.googleapis.com/auth/classroom.rosters
#' \item https://www.googleapis.com/auth/classroom.rosters.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.profile.emails, https://www.googleapis.com/auth/classroom.profile.photos, https://www.googleapis.com/auth/classroom.rosters, https://www.googleapis.com/auth/classroom.rosters.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param userId Identifier of the profile to return
#' @importFrom googleAuthR gar_api_generator
#' @export
userProfiles.get <- function(userId) {
    url <- sprintf("https://classroom.googleapis.com/v1/userProfiles/%s", userId)
    # classroom.userProfiles.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Creates an invitation. Only one invitation for a user and course may exist at a time. Delete and re-create an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course or for access errors. * `NOT_FOUND` if the course or the user does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled or if the user already has this role or a role with greater permissions. * `ALREADY_EXISTS` if an invitation for the specified user and course already exists.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.rosters
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.rosters)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Invitation The \link{Invitation} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family Invitation functions
#' @export
invitations.create <- function(Invitation) {
    url <- "https://classroom.googleapis.com/v1/invitations"
    # classroom.invitations.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Invitation, "gar_Invitation"))
    
    f(the_body = Invitation)
    
}

#' Returns an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.rosters
#' \item https://www.googleapis.com/auth/classroom.rosters.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.rosters, https://www.googleapis.com/auth/classroom.rosters.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param id Identifier of the invitation to return
#' @importFrom googleAuthR gar_api_generator
#' @export
invitations.get <- function(id) {
    url <- sprintf("https://classroom.googleapis.com/v1/invitations/%s", id)
    # classroom.invitations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Deletes an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.rosters
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.rosters)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param id Identifier of the invitation to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
invitations.delete <- function(id) {
    url <- sprintf("https://classroom.googleapis.com/v1/invitations/%s", id)
    # classroom.invitations.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the list request. *Note:* At least one of `user_id` or `course_id` must be supplied. Both fields can be supplied. This method returns the following error codes: * `PERMISSION_DENIED` for access errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.rosters
#' \item https://www.googleapis.com/auth/classroom.rosters.readonly
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.rosters, https://www.googleapis.com/auth/classroom.rosters.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param userId Restricts returned invitations to those for a specific user
#' @param courseId Restricts returned invitations to those for a course with the specified identifier
#' @param pageSize Maximum number of items to return
#' @param pageToken nextPageToken value returned from a previous list call, indicating that the subsequent page of results should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
invitations.list <- function(userId = NULL, courseId = NULL, pageSize = NULL, pageToken = NULL) {
    url <- "https://classroom.googleapis.com/v1/invitations"
    # classroom.invitations.list
    pars = list(userId = userId, courseId = courseId, pageSize = pageSize, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}


#' Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation or for access errors. * `FAILED_PRECONDITION` for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReached * UserGroupsMembershipLimitReached * `NOT_FOUND` if no invitation exists with the requested ID.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://developers.google.com/classroom/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/classroom.rosters
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/classroom.rosters)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param id Identifier of the invitation to accept
#' @importFrom googleAuthR gar_api_generator
#' @export


invitations.accept <- function(id) {
    
    
    url <- sprintf("https://classroom.googleapis.com/v1/invitations/%s:accept", id)
    # classroom.invitations.accept
    
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    
    f()
    
    
}



